import 'package:diasguto/models/chant.dart';
import 'package:diasguto/templates/cipher.dart';

List<Chant> aclamation = [
  quandoEstamosUnidos,
  tuaPalavra,
  minhaAlmaAbrirei,
  buscaiPrimeiro,
  palavraDeSalvacao,
  versiculoDoDia,
  euVosDouUmNovoMandamento,
  louvorEGloriaII,
  louvorEGloria,
  comoSaoBelosOsPes,
  rendeiGracasAoSenhor,
  noPrincipioEraAPalavra
];

Chant quandoEstamosUnidos = Chant(
    title: 'Quando estamos unidos',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: 'Aleluia, aleluia, aleluia'),
      const Music(cipher: 'Aleluia, aleluia, aleluia'),
      const Music(cipher: ''),
      const Music(cipher: 'Quando estamos unidos, estás entre nós'),
      const Music(cipher: 'E nos falarás da tua vida'),
      const Music(cipher: 'Este nosso mundo sentido terá'),
      const Music(cipher: 'Se tua palavra renovar'),
      const Music(cipher: ''),
      const Music(cipher: ''),
      const Music(cipher: 'Aleluia, aleluia, aleluia'),
      const Music(cipher: 'Aleluia, aleluia, aleluia'),
    ],
    hasCypher: false,
    ciphers: []);

Chant tuaPalavra = Chant(
    title: 'Tua palavra',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: ''),
      const Music(cipher: 'Aleluia, aleluia, aleluia!'),
      const Music(cipher: 'Aleluia, aleluia, aleluia!'),
      const Music(cipher: ''),
      const Music(cipher: 'Tua palavra é como fogo'),
      const Music(cipher: 'Que faz arder o coração'),
      const Music(cipher: 'Traz a verdade e ilumina a nossa vida'),
      const Music(cipher: ''),
      const Music(cipher: 'Tua palavra é como fogo'),
      const Music(cipher: 'Que faz arder o coração'),
      const Music(cipher: 'Traz a verdade e ilumina a nossa vida'),
      const Music(cipher: ''),
      const Music(cipher: 'Aleluia, aleluia, aleluia!'),
      const Music(cipher: 'Aleluia, aleluia, aleluia!'),
    ],
    hasCypher: false,
    ciphers: []);

Chant minhaAlmaAbrirei = Chant(
    title: 'Minha alma abrirei',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: "ALELUIA, ALELUIA, A MINH'ALMA ABRIREI"),
      const Music(cipher: 'ALELUIA, ALELUIA, CRISTO É MEU REI.'),
      const Music(cipher: "ALELUIA, ALELUIA, A MINH'ALMA ABRIREI"),
      const Music(cipher: 'ALELUIA, ALELUIA, CRISTO É MEU REI.'),
    ],
    hasCypher: true,
    ciphers: [
      const Cifra(cipher: 'C G/B Am Em F Dm G G7'),
      const Music(cipher: "ALELUIA, ALELUIA, A MINH'ALMA ABRIREI"),
      const Cifra(cipher: 'C G/B Am Em F G C A7'),
      const Music(cipher: 'ALELUIA, ALELUIA, CRISTO É MEU REI.'),
      const Cifra(cipher: 'D A/C# Bm F#m G Em A A7'),
      const Music(cipher: "ALELUIA, ALELUIA, A MINH'ALMA ABRIREI"),
      const Cifra(cipher: 'D A/C# Bm F#m G A D'),
      const Music(cipher: 'ALELUIA, ALELUIA, CRISTO É MEU REI.'),
    ]);

Chant buscaiPrimeiro = Chant(
    title: 'Buscai primeiro',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: 'BUSCAI PRIMEIRO O REINO DE DEUS'),
      const Music(cipher: 'E A SUA JUSTIÇA'),
      const Music(cipher: 'E TUDO MAIS VOS SERÁ ACRESCENTADO'),
      verse(),
      const Music(cipher: 'ALELUIA! ALELUIA!'),
      const Music(cipher: 'NÃO SÓ DE PÃO O HOMEM VIVERÁ,'),
      const Music(cipher: 'MAS DE TODA PALAVRA'),
      const Music(cipher: 'QUE PROCEDE DA BOCA DE DEUS'),
      verse(),
      const Music(cipher: 'ALELUIA! ALELUIA!'),
      const Music(cipher: 'SE VOS PERSEGUEM POR CAUSA DE MIM'),
      const Music(cipher: 'NÃO ESQUEÇAIS O PORQUÊ'),
      verse(),
      const Music(cipher: 'NÃO É O SERVO MAIOR QUE O SENHOR'),
      const Music(cipher: 'ALELUIA! ALELUIA!'),
    ],
    hasCypher: true,
    ciphers: [
      const Cifra(cipher: 'C          G       Am        Em'),
      const Music(cipher: 'BUSCAI PRIMEIRO O REINO DE DEUS'),
      const Cifra(cipher: 'F    C       G'),
      const Music(cipher: 'E A SUA JUSTIÇA'),
      const Cifra(cipher: 'C       G        Am            Em'),
      const Music(cipher: 'E TUDO MAIS VOS SERÁ ACRESCENTADO'),
      verse(),
      const Cifra(cipher: 'F     C   G     C'),
      const Music(cipher: 'ALELUIA! ALELUIA!'),
      const Music(cipher: 'NÃO SÓ DE PÃO O HOMEM VIVERÁ,'),
      const Music(cipher: 'MAS DE TODA PALAVRA'),
      const Music(cipher: 'QUE PROCEDE DA BOCA DE DEUS'),
      verse(),
      const Music(cipher: 'ALELUIA! ALELUIA!'),
      const Music(cipher: 'SE VOS PERSEGUEM POR CAUSA DE MIM'),
      const Music(cipher: 'NÃO ESQUEÇAIS O PORQUÊ'),
      verse(),
      const Music(cipher: 'NÃO É O SERVO MAIOR QUE O SENHOR'),
      const Music(cipher: 'ALELUIA! ALELUIA!'),
    ]);

Chant palavraDeSalvacao = Chant(
    title: 'Palavra de Salvação',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: 'Palavra de salvação'),
      const Music(cipher: 'somente o céu tem pra dar'),
      const Music(cipher: 'Por isso meu coração'),
      const Music(cipher: 'se abre para escutar'),
      verse(),
      const Music(cipher: 'Por mais difícil que seja seguir'),
      const Music(cipher: 'Tua palavra queremos ouvir'),
      const Music(cipher: 'Por mais difícil de se praticar'),
      const Music(cipher: 'Tua palavra queremos guardar'),
      verse(),
      const Music(cipher: 'Palavra de salvação'),
      const Music(cipher: 'somente o céu tem pra dar'),
      const Music(cipher: 'Por isso meu coração'),
      const Music(cipher: 'se abre para escutar'),
      verse(),
      const Music(cipher: 'Com Simão Pedro diremos também'),
      const Music(cipher: 'Que não é fácil dizer sempre amém'),
      const Music(cipher: 'Mas não há outro na Terra e no céu'),
      const Music(cipher: 'Mais companheiro, mais santo e fiel'),
      verse(),
    ],
    hasCypher: true,
    ciphers: [
      const Cifra(cipher: '  E            B7'),
      const Music(cipher: 'Palavra de salvação'),
      const Cifra(cipher: ' F#m       B7           E'),
      const Music(cipher: 'somente o céu tem pra dar'),
      const Cifra(cipher: '                  B7'),
      const Music(cipher: 'Por isso meu coração'),
      const Music(cipher: '    A    B7     E   E7'),
      const Music(cipher: 'se abre para escutar'),
      verse(),
      const Music(cipher: 'A           E          B7      E  E7'),
      const Music(cipher: 'POR MAIS DIFÍCIL QUE SEJA SEGUIR'),
      const Music(cipher: 'A      E       B7       E   E7'),
      const Music(cipher: 'TUA PALAVRA QUEREMOS OUVIR'),
      const Music(cipher: 'A          E        B7        E E7'),
      const Music(cipher: 'POR MAIS DIFÍCIL DE SE PRATICAR'),
      const Music(cipher: 'A       E       B7         E B7'),
      const Music(cipher: 'TUA PALAVRA QUEREMOS GUARDAR'),
      verse(),
      const Music(cipher: 'COM SIMÃO PEDRO DIREMOS TAMBÉM'),
      const Music(cipher: 'QUE NÃO É FÁCIL DIZER SEMPRE AMÉM'),
      const Music(cipher: 'MAS NÃO HÁ OUTRO NA TERRA E NO CÉU'),
      const Music(cipher: 'MAIS COMPANHEIRO, MAIS SANTO E FIEL'),
    ]);

Chant versiculoDoDia = Chant(
    title: 'Versiculo do Dia',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: 'D Em F#m G A7 D A7'),
      const Music(cipher: 'ALELUIA ALELUIA ALELUIA! ALELUIA (2X)'),
      const Music(cipher: 'D G'),
      const Music(cipher: 'O HOMEM NÃO VIVE SOMENTE DE PÃO'),
      const Music(cipher: 'Em A7'),
      const Music(cipher: 'MAS DE TODA A PALAVRA DA BOCA DE DEUS'),
    ],
    hasCypher: false,
    ciphers: []);

Chant euVosDouUmNovoMandamento = Chant(
    title: 'Eu vos dou um novo mandamento',
    category: 'Aclamação',
    lyrics: [
      verse(),
      verse(),
      const Music(cipher: 'EU VOS DOU UM NOVO MANDAMENTO.'),
      const Music(cipher: '"QUE VOS AMEIS UNS AOS OUTROS,'),
      const Music(cipher: 'ASSIM COMO EU VOS AMEI",'),
      const Music(cipher: 'DISSE O SENHOR. (2X)'),
    ],
    hasCypher: true,
    ciphers: [
      verse(),
      verse(),
      const Music(cipher: 'A   E    A      D   E      A E A'),
      const Music(cipher: 'EU VOS DOU UM NOVO MANDAMENTO.'),
      const Music(cipher: '           D             A'),
      const Music(cipher: '"QUE VOS AMEIS UNS AOS OUTROS,'),
      const Music(cipher: '  D         A  E7    A'),
      const Music(cipher: 'ASSIM COMO EU VOS AMEI",'),
      const Music(cipher: 'D     E7    A'),
      const Music(cipher: 'DISSE O SENHOR. (2X)'),
    ]);

Chant louvorEGloriaII = Chant(
    title: 'Louvor e Gloria 2',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: 'Louvor e glória a ti, Senhor,'),
      const Music(cipher: 'Cristo palavra de Deus,'),
      const Music(cipher: 'Cristo palavra de Deus!'),
      verse(),
      const Music(cipher: 'Numa nuvem  resplendente'),
      const Music(cipher: 'fez-se ouvir a voz do Pai'),
      const Music(cipher: 'Eis meu filho muito amado,'),
      const Music(cipher: 'Escutai-o todos vós!'),
    ],
    hasCypher: true,
    ciphers: [
      const Music(cipher: 'G          G/B    C       G'),
      const Music(cipher: 'LOUVOR E GLÓRIA A TI, SENHOR'),
      const Music(cipher: ' C       D7         G  D/F# Em'),
      const Music(cipher: 'CRISTO PALAVRA DE DEUS'),
      const Music(cipher: 'Am      D7          G'),
      const Music(cipher: 'CRISTO PALAVRA DE DEUS'),
      const Music(cipher: 'G                      '),
      const Music(cipher: 'NUMA NUVEM RESPLENDENTE'),
      const Music(cipher: '                        D'),
      const Music(cipher: 'FEZ-SE OUVIR A VOZ DO PAI'),
      const Music(cipher: 'G  '),
      const Music(cipher: '“EIS MEU FILHO MUITO AMADO,'),
      const Music(cipher: '                   D'),
      const Music(cipher: ' ESCUTAI-O TODOS VÓS”')
    ]);

Chant louvorEGloria = Chant(
    title: 'Louvor e Glória',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: 'Louvor e glória a ti, Senhor,'),
      const Music(cipher: 'Cristo palavra, palavra de Deus!'),
      verse(),
      const Music(cipher: 'O Homem não vive'),
      const Music(cipher: 'Somente de pão,'),
      const Music(cipher: 'Mas de toda palavra'),
      const Music(cipher: 'Da boca de Deus!'),
    ],
    hasCypher: false,
    ciphers: [
      const Cifra(cipher: '   D       D7     G        D'),
      const Music(cipher: 'LOUVOR E GLÓRIA A TI, SENHOR'),
      const Cifra(cipher: 'Em       F#m       G   A      D'),
      const Music(cipher: 'CRISTO PALAVRA, PALAVRA DE DEUS (2X)'),
      const Cifra(cipher: 'D                            G'),
      const Music(cipher: 'O HOMEM NÃO VIVE SOMENTE DE PÃO'),
      const Cifra(cipher: 'Em                                A'),
      const Music(cipher: 'MAS DE TODA PALAVRA DA BOCA DE DEUS'),
    ]);

Chant comoSaoBelosOsPes = Chant(
    title: 'Como São belos os pés do Mensageiro',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: 'Como são belos os pés do mensageiro'),
      const Music(cipher: 'Que anuncia a paz'),
      const Music(cipher: 'Como são belos os pés do mensageiro'),
      const Music(cipher: 'Que anuncia o Senhor'),
      const Music(cipher: ''),
      const Music(cipher: 'Ele vive, Ele reina'),
      const Music(cipher: 'Ele é Deus e Senhor'),
      const Music(cipher: 'Ele vive, Ele reina'),
      const Music(cipher: 'Ele é Deus e Senhor'),
      const Music(cipher: ''),
      const Music(cipher: 'O meu Senhor chegou com toda a glória'),
      const Music(cipher: 'E vivo, eu sei, Ele está'),
      const Music(cipher: 'Bem junto a nós, Seu corpo santo a nos tocar'),
      const Music(cipher: 'E vivo, eu sei, Ele está'),
      const Music(cipher: ''),
      const Music(cipher: 'Porque Ele vive, Ele reina'),
      const Music(cipher: 'Ele é Deus e Senhor'),
      const Music(cipher: 'Porque Ele vive, Ele reina'),
      const Music(cipher: 'Ele é Deus e Senhor'),
      const Music(cipher: ''),
      const Music(cipher: 'Porque Ele vive, Ele reina'),
      const Music(cipher: 'Ele é Deus e Senhor'),
      const Music(cipher: 'Porque Ele vive, Ele reina'),
      const Music(cipher: 'Ele é Deus e Senhor'),
      const Music(cipher: ''),
      const Music(cipher: 'Porque Ele vive, Ele reina'),
      const Music(cipher: 'Ele é Deus e Senhor'),
      const Music(cipher: 'Porque Ele vive, Ele reina'),
      const Music(cipher: 'Ele é Deus e Senhor'),
      const Music(cipher: ''),
    ],
    hasCypher: false,
    ciphers: []);

Chant rendeiGracasAoSenhor = Chant(
    title: 'Rendei Graças ao Senhor',
    category: 'Aclamação',
    lyrics: [
      const Music(cipher: 'ALELUIA ALELUIA ALELUIA! ALELUIA (2X)'),
      const Music(cipher: 'RENDEI GRAÇAS AO SENHOR'),
      const Music(cipher: 'QUE SEU AMOR É SEM FIM!'),
      const Music(cipher: 'DIGA O POVO DE ISRAEL:'),
      const Music(cipher: 'QUE SEU AMOR É SEM FIM!'),
      const Music(cipher: 'DIGAM OS SEUS SACERDOTES:'),
      const Music(cipher: 'QUE SEU AMOR É SEM FIM!'),
      const Music(cipher: 'DIGAM TODOS OS CRISTÃOS:'),
      const Music(cipher: 'QUE SEU AMOR É SEM FIM!'),
    ],
    hasCypher: true,
    ciphers: [
      const Cifra(cipher: '    D      Em      F#m    G A7 D'),
      const Music(cipher: 'ALELUIA ALELUIA ALELUIA! ALELUIA (2X)'),
      const Cifra(cipher: '   D                  A'),
      const Music(cipher: 'RENDEI GRAÇAS AO SENHOR'),
      const Cifra(cipher: 'Em       A7         D'),
      const Music(cipher: 'QUE SEU AMOR É SEM FIM!'),
      const Cifra(cipher: '         D           A'),
      const Music(cipher: 'DIGA O POVO DE ISRAEL:'),
      const Cifra(cipher: 'Em       A7         D'),
      const Music(cipher: 'QUE SEU AMOR É SEM FIM!'),
      const Cifra(cipher: '          A             D'),
      const Music(cipher: 'DIGAM OS SEUS SACERDOTES:'),
      const Cifra(cipher: '  G       D           A'),
      const Music(cipher: 'QUE SEU AMOR É SEM FIM!'),
      const Cifra(cipher: '        D'),
      const Music(cipher: 'DIGAM TODOS OS CRISTÃOS:'),
      const Cifra(cipher: 'G        Em           A'),
      const Music(cipher: 'QUE SEU AMOR É SEM FIM!'),
    ]);

Chant noPrincipioEraAPalavra = Chant(
    title: 'No princípio era a palavra',
    category: 'Aclamação',
    lyrics: [
      verse(),
      verse(),
      const Music(cipher: 'ALELUIA, ALELUIA (2X)'),
      verse(),
      const Music(cipher: 'NO PRINCÍPIO ERA A PALAVRA'),
      const Music(cipher: 'E A PALAVRA SE ENCARNOU'),
      const Music(cipher: 'E NÓS VIMOS SUA GLÓRIA'),
      const Music(cipher: 'SEU AMOR NOS LIBERTOU'),
    ],
    hasCypher: true,
    ciphers: [
      verse(),
      verse(),
      const Cifra(cipher: 'G C G D G'),
      const Music(cipher: 'ALELUIA, ALELUIA (2X)'),
      verse(),
      const Cifra(cipher: 'G C'),
      const Music(cipher: 'NO PRINCÍPIO ERA A PALAVRA'),
      const Cifra(cipher: 'D G'),
      const Music(cipher: 'E A PALAVRA SE ENCARNOU'),
      const Cifra(cipher: 'C'),
      const Music(cipher: 'E NÓS VIMOS SUA GLÓRIA'),
      const Cifra(cipher: 'D G D7'),
      const Music(cipher: 'SEU AMOR NOS LIBERTOU'),
    ]);
