import 'package:diasguto/models/chant.dart';
import 'package:diasguto/templates/cipher.dart';

List<Chant> ending = [
  vouNavegar,
  mariaDeMinhaInfancia,
  pelasEstradasDaVida,
  aEscolhida,
  chuvaDeGraca,
  esAEscolhida,
  quemEEsta,
  seguraNaMaodeDeus,
  oracaoPelaFamilia,
  facoNovasTodasasCoisas,
  mariaDeNazare,
  santaMaeMaria
];

Chant vouNavegar = Chant(
    title: 'Vou navegar',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'Outra vez me vejo só, com meu Deus'),
      const Music(cipher: 'Não consigo mais fugir, fugir de mim'),
      const Music(cipher: 'Junto às águas deste mar vou lutar'),
      const Music(cipher: 'Hoje quero me encontrar'),
      const Music(cipher: 'Buscar o meu lugar'),
      verse(),
      const Music(cipher: 'Vou navegar, nas águas deste mar'),
      const Music(cipher: 'Navegar... eu quero me encontrar'),
      const Music(cipher: 'Navegar... não posso mais fugir'),
      const Music(cipher: 'Vou procurar, nas águas mais profundas'),
      const Music(cipher: 'No mar... feliz eu vou seguir'),
      const Music(cipher: 'Só amar, buscar o meu lugar'),
      const Music(cipher: 'Sem dúvidas, sem medo de sonhar!'),
      verse(),
      const Music(cipher: 'Ó Jesus, com fé eu te seguirei'),
      const Music(cipher: 'Só contigo sou feliz, tu és em mim!'),
      const Music(cipher: 'Teu espírito de amor criador'),
      const Music(cipher: 'Me sustenta no meu sim'),
      const Music(cipher: 'Me lança neste mar!'),
      verse(),
      const Music(cipher: 'Vivo a certeza desta missão'),
      const Music(cipher: 'Já não posso desistir, voltar atrás'),
      const Music(cipher: 'Mãe Maria, vem tomar minha mão'),
      const Music(cipher: 'E me ajuda a ser fiel'),
      const Music(cipher: 'Só Cristo é luz e paz!'),
    ],
    hasCypher: false);

Chant mariaDeMinhaInfancia = Chant(
    title: 'Maria de minha infância',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'Eu era pequeno, nem me lembro'),
      const Music(cipher: 'Só lembro que à noite, ao pé da cama'),
      const Music(cipher: 'Juntava as mãozinhas e rezava apressado'),
      const Music(cipher: 'Mas rezava como alguém que ama'),
      const Music(cipher: 'Nas Ave Marias que eu rezava'),
      const Music(cipher: 'Eu sempre engolia umas palavras'),
      const Music(cipher: 'E muito cansado acabava dormindo'),
      const Music(cipher: 'Mas dormia como quem amava'),
      verse(),
      const Music(cipher: 'Ave Maria, Mãe de Jesus'),
      const Music(cipher: 'O tempo passa, não volta mais'),
      const Music(cipher: 'Tenho saudade daquele tempo'),
      const Music(cipher: 'Que eu te chamava de minha mãe'),
      const Music(cipher: 'Ave Maria, Mãe de Jesus'),
      const Music(cipher: 'Ave Maria, Mãe de Jesus'),
      verse(),
      const Music(cipher: 'Depois fui crescendo, eu me lembro'),
      const Music(cipher: 'E fui esquecendo nossa amizade'),
      const Music(cipher: 'Chegava lá em casa chateado e cansado'),
      const Music(cipher: 'De rezar não tinha nem vontade'),
      const Music(cipher: 'Andei duvidando, eu me lembro'),
      const Music(cipher: 'Das coisas mais puras que me ensinaram'),
      const Music(cipher: 'Perdi o costume da criança inocente'),
      const Music(cipher: 'Minhas mãos quase não se ajuntavam'),
      verse(),
      const Music(cipher: 'O teu amor cresce com a gente'),
      const Music(cipher: 'A mãe nunca esquece o filho ausente'),
      const Music(cipher: 'Eu chego lá em casa chateado e cansado'),
      const Music(cipher: 'Mas eu rezo como antigamente'),
      const Music(cipher: 'Nas Ave Marias que hoje eu rezo'),
      const Music(cipher: 'Esqueço as palavras e adormeço'),
      const Music(cipher: 'E embora cansado, sem rezar como eu devo'),
      const Music(cipher: 'Eu de Ti Maria, não me esqueço'),
    ],
    hasCypher: false);

Chant pelasEstradasDaVida = Chant(
    title: 'Pelas estradas da vida',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'Pelas estradas da vida, nunca sozinho estás'),
      const Music(cipher: 'Contigo pelo caminho, Santa Maria vai'),
      verse(),
      const Refrao(cipher: 'Ó vem conosco, vem caminhar,'),
      const Refrao(cipher: 'Santa Maria vem (bis)'),
      verse(),
      const Music(cipher: 'Se pelo mundo os homens, sem conhecer-se vão'),
      const Music(cipher: 'Não negues nunca a tua mão a quem te encontrar'),
      verse(),
      const Refrao(cipher: 'Ó vem conosco, vem caminhar,'),
      const Refrao(cipher: 'Santa Maria vem (bis)'),
      verse(),
      const Music(cipher: 'Mesmo que digam os homens, tu nada podes mudar'),
      const Music(cipher: 'Luta por um mundo novo de unidade e paz'),
      verse(),
      const Refrao(cipher: 'Ó vem conosco, vem caminhar,'),
      const Refrao(cipher: 'Santa Maria vem (bis)'),
      verse(),
      const Music(cipher: 'Se parecer tua vida inútil caminhar'),
      const Music(cipher: 'Lembra que abres caminho, outros te seguirão'),
      verse(),
      const Refrao(cipher: 'Ó vem conosco, vem caminhar,'),
      const Refrao(cipher: 'Santa Maria vem (bis)'),
    ],
    hasCypher: false);

Chant aEscolhida = Chant(
    title: 'A escolhida',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'Uma entre todas foi a escolhida'),
      const Music(cipher: 'Fostes tu, Maria, a serva preferida'),
      const Music(cipher: 'Mãe do meu Senhor'),
      const Music(cipher: 'Mãe do meu salvador'),
      verse(),
      const Refrao(cipher: 'Maria, cheia de graça e consolo'),
      const Refrao(cipher: 'Venha caminhar com teu povo'),
      const Refrao(cipher: 'Nossa mãe sempre será (bis)'),
      verse(),
      const Music(cipher: 'Roga pelos pecadores desta Terra'),
      const Music(cipher: 'Roga pelo povo em que seu Deus espera'),
      const Music(cipher: 'Mãe do meu Senhor mãe do meu salvador'),
      verse(),
      const Refrao(cipher: 'Maria, cheia de graça e consolo'),
      const Refrao(cipher: 'Venha caminhar com teu povo'),
      const Refrao(cipher: 'Nossa mãe sempre será (bis)'),
      verse(),
    ],
    hasCypher: false);

Chant chuvaDeGraca = Chant(
    title: 'Chuva de graças',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'Há uma chuva de graça aqui'),
      const Music(cipher: 'Está chovendo sobre todos nós'),
      const Music(cipher: 'E quem mais se entregar'),
      const Music(cipher: 'Mais se molhará'),
      verse(),
      const Music(cipher: 'Há uma semente pra germinar'),
      const Music(cipher: 'E muitos frutos a se produzir'),
      const Music(cipher: 'Na terra do coração'),
      const Music(cipher: 'Derrama tua graça'),
      verse(),
      const Refrao(cipher: 'Chuva de graça, pedimos a Ti'),
      const Refrao(cipher: 'Chuva de graça, derrama em nós'),
      const Refrao(cipher: 'Chuva de graça neste lugar'),
      const Refrao(cipher: 'Derrama! (2x)'),
    ],
    hasCypher: false);

Chant esAEscolhida = Chant(
    title: 'És a escolhida',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'Doce Mãe de Deus olha para nós'),
      const Music(cipher: 'Pois, necessitamos de Ti'),
      const Music(cipher: 'Vem nos consolar com o teu amor'),
      const Music(cipher: 'Mostra-nos o teu Jesus (2x)'),
      verse(),
      const Music(cipher: 'Todo teu Maria eu quero ser'),
      const Music(cipher: 'Vou me consagrar'),
      const Music(cipher: 'A minha família e os meus irmãos'),
      const Music(cipher: 'Vem abençoar'),
      verse(),
      const Music(cipher: 'Maria és a escolhida de Deus'),
      const Music(cipher: 'Maria roga pelos filhos teus (2x)'),
    ],
    hasCypher: false);

Chant quemEEsta = Chant(
    title: 'Quem é esta que avança como a aurora',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'QUEM É ESTA QUE AVANÇA COMO A AURORA,'),
      const Music(cipher: 'TEMÍVEL COMO EXÉRCITO EM ORDEM DE BATALHA,'),
      const Music(cipher: 'BRILHANTE COMO O SOL E COMO A LUA,'),
      const Music(cipher: 'MOSTRANDO O CAMINHO AOS FILHOS SEUS.'),
      verse(),
      const Music(cipher: 'AH, AH, AH, MINHA ALMA GLORIFICA AO SENHOR,'),
      const Music(cipher: 'MEU ESPÍRITO EXULTA EM DEUS, MEU SALVADOR.'),
    ],
    hasCypher: false);

Chant seguraNaMaodeDeus = Chant(
    title: 'Segura na mão de Deus',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'Se as águas do mar da vida quiserem te afogar'),
      const Music(cipher: 'Segura na mão de Deus e vai'),
      const Music(cipher: 'Se as tristezas desta vida quiserem te sufocar'),
      const Music(cipher: 'Segura na mão de Deus e vai'),
      verse(),
      const Music(cipher: 'Segura na mão de Deus, segura na mão de Deus'),
      const Music(cipher: 'Pois ela, ela te sustentará'),
      const Music(cipher: 'Não temas, segue adiante e não olhes para trás'),
      const Music(cipher: 'Segura na mão de Deus e vai'),
      verse(),
      const Music(cipher: 'Se a jornada é pesada e te cansas da caminhada'),
      const Music(cipher: 'Segura na mão de Deus e vai'),
      const Music(cipher: 'Orando, jejuando, confiando e confessando'),
      const Music(cipher: 'Segura na mão de Deus e vai'),
      verse(),
      const Music(cipher: 'O Espírito do Senhor sempre te revestirá'),
      const Music(cipher: 'Segura na mão de Deus e vai'),
      const Music(cipher: 'Jesus Cristo prometeu que jamais te deixará'),
      const Music(cipher: 'Segura na mão de Deus e vai'),
    ],
    hasCypher: false);

Chant oracaoPelaFamilia = Chant(
    title: 'Oração pela família',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'Que nenhuma família comece em qualquer de repente'),
      const Music(cipher: 'Que nenhuma família termine por falta de amor'),
      const Music(
          cipher: 'Que o casal seja um para o outro de corpo e de mente'),
      const Music(cipher: 'E que nada no mundo separe um casal sonhador!'),
      verse(),
      const Refrao(cipher: 'Abençoa, Senhor, as famílias! Amém!'),
      const Refrao(cipher: 'Abençoa, Senhor, a minha também (2x)'),
      verse(),
      const Music(cipher: 'Que nenhuma família se abrigue debaixo da ponte'),
      const Music(cipher: 'Que ninguém interfira no lar e na vida dos dois'),
      const Music(
          cipher: 'Que ninguém os obrigue a viver sem nenhum horizonte'),
      const Music(
          cipher: 'Que eles vivam do ontem, do hoje em função de um depois'),
      verse(),
      const Refrao(cipher: 'Abençoa, Senhor, as famílias! Amém!'),
      const Refrao(cipher: 'Abençoa, Senhor, a minha também (2x)'),
      verse(),
      const Music(cipher: 'Que a família comece e termine sabendo onde vai'),
      const Music(
          cipher: 'E que o homem carregue nos ombros a graça de um pai'),
      const Music(
          cipher: 'Que a mulher seja um céu de ternura, aconchego e calor'),
      const Music(
          cipher: 'E que os filhos conheçam a força que brota do amor!'),
      verse(),
      const Refrao(cipher: 'Abençoa, Senhor, as famílias! Amém!'),
      const Refrao(cipher: 'Abençoa, Senhor, a minha também (2x)'),
      verse(),
      const Music(
          cipher: 'Que marido e mulher tenham força de amar sem medida'),
      const Music(
          cipher: 'Que ninguém vá dormir sem pedir ou sem dar seu perdão'),
      const Music(
          cipher: 'Que as crianças aprendam no colo, o sentido da vida'),
      const Music(
          cipher: 'Que a família celebre a partilha do abraço e do pão!'),
      verse(),
      const Refrao(cipher: 'Abençoa, Senhor, as famílias! Amém!'),
      const Refrao(cipher: 'Abençoa, Senhor, a minha também (2x)'),
      verse(),
      const Music(
          cipher: 'Que marido e mulher não se traiam, nem traiam seus filhos'),
      const Music(
          cipher: 'Que o ciúme não mate a certeza do amor entre os dois'),
      const Music(
          cipher: 'Que no seu firmamento a estrela que tem maior brilho'),
      const Music(
          cipher: 'Seja a firme esperança de um céu aqui mesmo e depois'),
      verse(),
      const Refrao(cipher: 'Abençoa, Senhor, as famílias! Amém!'),
      const Refrao(cipher: 'Abençoa, Senhor, a minha também (2x)'),
      verse(),
    ],
    hasCypher: false);

Chant facoNovasTodasasCoisas = Chant(
    title: 'Faço novas todas as coisas',
    category: 'Encerramento',
    lyrics: [
      const Refrao(cipher: 'Eis que faço novas todas as coisas,'),
      const Refrao(cipher: 'Que faço novas todas as coisas,'),
      const Refrao(cipher: 'Que faço novas todas as coisas. (2x)'),
      verse(),
      const Music(
          cipher:
              'É vida que brota da vida, é fruto que cresce do amor, é vida que vence a morte, é vida que vem do Senhor. (2x)'),
      verse(),
      const Refrao(cipher: 'Eis que faço novas todas as coisas,'),
      const Refrao(cipher: 'Que faço novas todas as coisas,'),
      const Refrao(cipher: 'Que faço novas todas as coisas. (2x)'),
      verse(),
      const Music(
          cipher:
              'Deixei o sepulcro vazio, a morte não me segurou, a pedra que então me prendia no terceiro dia rolou. (2x)'),
      verse(),
      const Refrao(cipher: 'Eis que faço novas todas as coisas,'),
      const Refrao(cipher: 'Que faço novas todas as coisas,'),
      const Refrao(cipher: 'Que faço novas todas as coisas. (2x)'),
      verse(),
      const Music(
          cipher:
              'Eu hoje lhe dou vida nova, renovo em ti o amor, lhe dou uma nova esperança, tudo o que era velho passou. (2x)'),
      verse(),
      const Refrao(cipher: 'Eis que faço novas todas as coisas,'),
      const Refrao(cipher: 'Que faço novas todas as coisas,'),
      const Refrao(cipher: 'Que faço novas todas as coisas. (2x)'),
      verse(),
    ],
    hasCypher: false);

Chant mariaDeNazare = Chant(
    title: 'Maria de Nazaré',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: '1. Maria de Nazaré, Maria me cativou'),
      const Music(cipher: 'Fez mais forte a minha fé'),
      const Music(cipher: 'E por filho me adotou'),
      verse(),
      const Music(cipher: '2. Às vezes eu paro e fico a pensar'),
      const Music(cipher: 'E sem perceber, me vejo a rezar'),
      const Music(cipher: 'E meu coração se põe a cantar'),
      const Music(cipher: 'Pra Virgem de Nazaré'),
      verse(),
      const Music(cipher: '3. Menina que Deus amou e escolheu'),
      const Music(cipher: 'Pra mãe de Jesus, o Filho de Deus'),
      const Music(cipher: 'Maria que o povo inteiro elegeu'),
      const Music(cipher: 'Senhora e Mãe do Céu'),
      verse(),
      const Refrao(cipher: 'Ave Maria, Ave Maria'),
      const Refrao(cipher: 'Ave Maria, Mãe de Jesus! (bis)'),
      verse(),
      const Music(cipher: '4. Maria que eu quero bem, Maria do puro amor'),
      const Music(cipher: 'Igual a você, ninguém'),
      const Music(cipher: 'Mãe pura do meu Senhor'),
      verse(),
      const Music(cipher: '5. Em cada mulher que a terra criou'),
      const Music(cipher: 'Um traço de Deus Maria deixou'),
      const Music(cipher: 'Um sonho de Mãe Maria plantou'),
      const Music(cipher: 'Pro mundo encontrar a paz'),
      const Music(cipher: 'Maria que fez o Cristo falar'),
      const Music(cipher: 'Maria que fez Jesus caminhar'),
      const Music(cipher: 'Maria que só viveu pra seu Deus'),
      const Music(cipher: 'Maria do povo meu'),
      verse(),
      const Refrao(cipher: 'Ave Maria, Ave Maria'),
      const Refrao(cipher: 'Ave Maria, Mãe de Jesus! (bis)'),
      verse(),
    ],
    hasCypher: false);

Chant santaMaeMaria = Chant(
    title: 'Santa Mãe Maria',
    category: 'Encerramento',
    lyrics: [
      const Music(cipher: 'Santa Mãe Maria, nessa travessia'),
      const Music(cipher: 'Cubra-nos teu manto cor de anil'),
      const Music(cipher: 'Guarda nossa vida, Mãe Aparecida'),
      const Music(cipher: 'Santa padroeira do Brasil'),
      verse(),
      const Refrao(cipher: 'Ave, Maria! Ave, Maria!'),
      const Refrao(cipher: 'Ave, Maria! Ave, Maria! (bis)'),
      verse(),
      const Music(cipher: 'Com amor divino guarda os peregrinos'),
      const Music(cipher: 'Nesta caminhada para o além'),
      const Music(cipher: 'Dá-lhes companhia, pois também um dia'),
      const Music(cipher: 'Foste peregrina em Belém'),
      verse(),
      const Refrao(cipher: 'Ave, Maria! Ave, Maria!'),
      const Refrao(cipher: 'Ave, Maria! Ave, Maria! (bis)'),
      verse(),
      const Music(cipher: 'Mulher peregrina, força feminina'),
      const Music(cipher: 'A mais importante que existiu'),
      const Music(cipher: 'Com justiça queres que nossas mulheres'),
      const Music(cipher: 'Sejam construtoras do Brasil'),
      verse(),
      const Refrao(cipher: 'Ave, Maria! Ave, Maria!'),
      const Refrao(cipher: 'Ave, Maria! Ave, Maria! (bis)'),
      verse(),
      const Music(cipher: 'Com seus passos lentos enfrentando os ventos'),
      const Music(cipher: 'Quando sopram noutra direção'),
      const Music(cipher: 'Toda a mãe Igreja pede que tu sejas'),
      const Music(cipher: 'Companheira de libertação'),
      verse(),
      const Refrao(cipher: 'Ave, Maria! Ave, Maria!'),
      const Refrao(cipher: 'Ave, Maria! Ave, Maria! (bis)'),
      verse(),
    ],
    hasCypher: false);
