import 'package:diasguto/models/chant.dart';
import 'package:diasguto/templates/cipher.dart';

List<Chant> ending = [
  vouNavegar,
  mariaDeMinhaInfancia,
  pelasEstradasDaVida,
  aEscolhida,
  chuvaDeGraca,
  esAEscolhida,
  quemEEsta,
  seguraNaMaodeDeus,
  oracaoPelaFamilia,
  facoNovasTodasasCoisas,
  mariaDeNazare,
  santaMaeMaria
];

Chant vouNavegar =
    Chant(title: 'Vou navegar', category: 'Encerramento', ciphers: [
  const Music(cipher: 'Outra vez me vejo só, com meu Deus'),
  const Music(cipher: 'Não consigo mais fugir, fugir de mim'),
  const Music(cipher: 'Junto às águas deste mar vou lutar'),
  const Music(cipher: 'Hoje quero me encontrar'),
  const Music(cipher: 'Buscar o meu lugar'),
  const Music(cipher: ''),
  const Music(cipher: 'Vou navegar, nas águas deste mar'),
  const Music(cipher: 'Navegar... eu quero me encontrar'),
  const Music(cipher: 'Navegar... não posso mais fugir'),
  const Music(cipher: 'Vou procurar, nas águas mais profundas'),
  const Music(cipher: 'No mar... feliz eu vou seguir'),
  const Music(cipher: 'Só amar, buscar o meu lugar'),
  const Music(cipher: 'Sem dúvidas, sem medo de sonhar!'),
  const Music(cipher: ''),
  const Music(cipher: 'Ó Jesus, com fé eu te seguirei'),
  const Music(cipher: 'Só contigo sou feliz, tu és em mim!'),
  const Music(cipher: 'Teu espírito de amor criador'),
  const Music(cipher: 'Me sustenta no meu sim'),
  const Music(cipher: 'Me lança neste mar!'),
  const Music(cipher: ''),
  const Music(cipher: 'Vivo a certeza desta missão'),
  const Music(cipher: 'Já não posso desistir, voltar atrás'),
  const Music(cipher: 'Mãe Maria, vem tomar minha mão'),
  const Music(cipher: 'E me ajuda a ser fiel'),
  const Music(cipher: 'Só Cristo é luz e paz!'),
]);

Chant mariaDeMinhaInfancia =
    Chant(title: 'Maria de minha infância', category: 'Encerramento', ciphers: [
  const Music(cipher: 'Eu era pequeno, nem me lembro'),
  const Music(cipher: 'Só lembro que à noite, ao pé da cama'),
  const Music(cipher: 'Juntava as mãozinhas e rezava apressado'),
  const Music(cipher: 'Mas rezava como alguém que ama'),
  const Music(cipher: 'Nas Ave Marias que eu rezava'),
  const Music(cipher: 'Eu sempre engolia umas palavras'),
  const Music(cipher: 'E muito cansado acabava dormindo'),
  const Music(cipher: 'Mas dormia como quem amava'),
  const Music(cipher: ''),
  const Music(cipher: 'Ave Maria, Mãe de Jesus'),
  const Music(cipher: 'O tempo passa, não volta mais'),
  const Music(cipher: 'Tenho saudade daquele tempo'),
  const Music(cipher: 'Que eu te chamava de minha mãe'),
  const Music(cipher: 'Ave Maria, Mãe de Jesus'),
  const Music(cipher: 'Ave Maria, Mãe de Jesus'),
  const Music(cipher: ''),
  const Music(cipher: 'Depois fui crescendo, eu me lembro'),
  const Music(cipher: 'E fui esquecendo nossa amizade'),
  const Music(cipher: 'Chegava lá em casa chateado e cansado'),
  const Music(cipher: 'De rezar não tinha nem vontade'),
  const Music(cipher: 'Andei duvidando, eu me lembro'),
  const Music(cipher: 'Das coisas mais puras que me ensinaram'),
  const Music(cipher: 'Perdi o costume da criança inocente'),
  const Music(cipher: 'Minhas mãos quase não se ajuntavam'),
  const Music(cipher: ''),
  const Music(cipher: 'O teu amor cresce com a gente'),
  const Music(cipher: 'A mãe nunca esquece o filho ausente'),
  const Music(cipher: 'Eu chego lá em casa chateado e cansado'),
  const Music(cipher: 'Mas eu rezo como antigamente'),
  const Music(cipher: 'Nas Ave Marias que hoje eu rezo'),
  const Music(cipher: 'Esqueço as palavras e adormeço'),
  const Music(cipher: 'E embora cansado, sem rezar como eu devo'),
  const Music(cipher: 'Eu de Ti Maria, não me esqueço'),
]);

Chant pelasEstradasDaVida =
    Chant(title: 'Pelas estradas da vida', category: 'Encerramento', ciphers: [
  const Music(cipher: 'Pelas estradas da vida, nunca sozinho estás'),
  const Music(cipher: 'Contigo pelo caminho, Santa Maria vai'),
  const Music(cipher: ''),
  const Music(cipher: 'Ó vem conosco, vem caminhar,'),
  const Music(cipher: 'Santa Maria vem'),
  const Music(cipher: ''),
  const Music(cipher: 'Se pelo mundo os homens, sem conhecer-se vão'),
  const Music(cipher: 'Não negues nunca a tua mão a quem te encontrar'),
  const Music(cipher: ''),
  const Music(cipher: 'Ó vem conosco, vem caminhar,'),
  const Music(cipher: 'Santa Maria vem'),
  const Music(cipher: ''),
  const Music(cipher: 'Mesmo que digam os homens, tu nada podes mudar'),
  const Music(cipher: 'Luta por um mundo novo de unidade e paz'),
  const Music(cipher: ''),
  const Music(cipher: 'Ó vem conosco, vem caminhar,'),
  const Music(cipher: 'Santa Maria vem'),
  const Music(cipher: ''),
  const Music(cipher: 'Se parecer tua vida inútil caminhar'),
  const Music(cipher: 'Lembra que abres caminho, outros te seguirão'),
  const Music(cipher: ''),
  const Music(cipher: 'Ó vem conosco, vem caminhar,'),
  const Music(cipher: 'Santa Maria vem'),
]);

Chant aEscolhida =
    Chant(title: 'A escolhida', category: 'Encerramento', ciphers: [
  const Music(cipher: 'Uma entre todas foi a escolhida'),
  const Music(cipher: 'Fostes tu, Maria, a serva preferida'),
  const Music(cipher: 'Mãe do meu Senhor'),
  const Music(cipher: 'Mãe do meu salvador'),
  const Music(cipher: ''),
  const Music(cipher: 'Maria, cheia de graça e consolo'),
  const Music(cipher: 'Venha caminhar com teu povo'),
  const Music(cipher: 'Nossa mãe sempre será'),
  const Music(cipher: 'Maria, cheia de graça e consolo'),
  const Music(cipher: 'Venha caminhar com teu povo'),
  const Music(cipher: 'Nossa mãe sempre será'),
  const Music(cipher: ''),
  const Music(cipher: 'Roga pelos pecadores desta Terra'),
  const Music(cipher: 'Roga pelo povo em que seu Deus espera'),
  const Music(cipher: 'Mãe do meu Senhor mãe do meu salvador'),
  const Music(cipher: ''),
  const Music(cipher: 'Maria, cheia de graça e consolo'),
  const Music(cipher: 'Venha caminhar com teu povo'),
  const Music(cipher: 'Nossa mãe sempre será'),
  const Music(cipher: 'Maria, cheia de graça e consolo'),
  const Music(cipher: 'Venha caminhar com teu povo'),
  const Music(cipher: 'Nossa mãe sempre será'),
]);

Chant chuvaDeGraca =
    Chant(title: 'Chuva de graças', category: 'Encerramento', ciphers: [
  const Music(cipher: 'Há uma chuva de graça aqui'),
  const Music(cipher: 'Está chovendo sobre todos nós'),
  const Music(cipher: 'E quem mais se entregar'),
  const Music(cipher: 'Mais se molhará'),
  const Music(cipher: ''),
  const Music(cipher: 'Há uma semente pra germinar'),
  const Music(cipher: 'E muitos frutos a se produzir'),
  const Music(cipher: 'Na terra do coração'),
  const Music(cipher: 'Derrama tua graça'),
  const Music(cipher: ''),
  const Music(cipher: 'Chuva de graça, pedimos a Ti'),
  const Music(cipher: 'Chuva de graça, derrama em nós'),
  const Music(cipher: 'Chuva de graça neste lugar'),
  const Music(cipher: 'Derrama! (2x)'),
]);

Chant esAEscolhida =
    Chant(title: 'És a escolhida', category: 'Encerramento', ciphers: [
  const Music(cipher: 'C G/B Am7 C7'),
  const Music(cipher: 'DOCE MÃE DE DEUS OLHA PARA NÓS'),
  const Music(cipher: 'F C/E Dm7 G'),
  const Music(cipher: 'POIS NECESSITAMOS DE TI'),
  const Music(cipher: 'C G/B Am7 C7'),
  const Music(cipher: 'VEM NOS CONSOLAR COM O TEU AMOR'),
  const Music(cipher: 'F G C G/B'),
  const Music(cipher: 'MOSTRA-NOS O TEU JESUS (2X)'),
  const Music(cipher: 'Am7 Em7 F C'),
  const Music(cipher: 'TODO TEU MARIA EU QUERO SER'),
  const Music(cipher: 'Dm7 G'),
  const Music(cipher: 'VOU ME CONSAGRAR'),
  const Music(cipher: 'Am7 Em7 F C'),
  const Music(cipher: 'A MINHA FAMÍLIA E OS MEUS IRMÃOS'),
  const Music(cipher: 'Dm7 G C'),
  const Music(cipher: 'VEM ABENÇOAR'),
  const Music(cipher: 'Dm7 Em7 F G'),
  const Music(cipher: 'MARIA ÉS A ESCOLHIDA DE DEUS'),
  const Music(cipher: 'Dm7 Em7 F G C'),
  const Music(cipher: 'MARIA ROGA PELOS FILHOS TEUS (2X)'),
]);

Chant quemEEsta = Chant(
    title: 'Quem é esta que avança como a aurora',
    category: 'Encerramento',
    ciphers: [
      const Music(cipher: 'E B7 C#m'),
      const Music(cipher: 'QUEM É ESTA QUE AVANÇA COMO A AURORA,'),
      const Music(cipher: 'E B7 C#m'),
      const Music(cipher: 'TEMÍVEL COMO EXÉRCITO EM ORDEM DE BATALHA,'),
      const Music(cipher: 'E B7 C#m'),
      const Music(cipher: 'BRILHANTE COMO O SOL E COMO A LUA,'),
      const Music(cipher: 'E B7 C#m'),
      const Music(cipher: 'MOSTRANDO O CAMINHO AOS FILHOS SEUS.'),
      const Music(cipher: 'E B7 C#m'),
      const Music(cipher: 'AH, AH, AH, MINHA ALMA GLORIFICA AO SENHOR,'),
      const Music(cipher: 'E B7 C#m E B7 C#m'),
      const Music(cipher: 'MEU ESPÍRITO EXULTA EM DEUS, MEU SALVADOR.'),
    ]);

Chant seguraNaMaodeDeus =
    Chant(title: 'Segura na mão de Deus', category: 'Encerramento', ciphers: [
  const Music(cipher: 'D D7 G D'),
  const Music(cipher: 'SE AS ÁGUAS DO MAR DA VIDA QUISEREM TE AFOGAR'),
  const Music(cipher: 'Bm Em A'),
  const Music(cipher: 'SEGURA NA MÃO DE DEUS E VAI'),
  const Music(cipher: 'D D7 G D'),
  const Music(cipher: 'SE AS TRISTEZAS DESTA VIDA QUISEREM TE SUFOCAR'),
  const Music(cipher: 'Bm Em A D G D'),
  const Music(cipher: 'SEGURA NA MÃO DE DEUS E VAI'),
  const Music(cipher: 'D D7 G D'),
  const Music(cipher: 'SEGURA NA MÃO DE DEUS, SEGURA NA MÃO DE DEUS'),
  const Music(cipher: 'Bm Em A'),
  const Music(cipher: 'POIS ELA, ELA TE SUSTENTARÁ'),
  const Music(cipher: 'D D7 G D'),
  const Music(cipher: 'NÃO TEMAS SEGUE ADIANTE E NÃO OLHES PARA TRÁS'),
  const Music(cipher: 'Bm Em A D G D'),
  const Music(cipher: 'SEGURA NA MÃO DE DEUS E VAI'),
  const Music(cipher: 'SE A JORNADA É PESADA E TE CANSAS DA CAMINHADA'),
  const Music(cipher: 'SEGURA NA MÃO DE DEUS E VAI'),
  const Music(cipher: 'ORANDO, JEJUANDO, CONFIANDO E CONFESSANDO'),
  const Music(cipher: 'SEGURA NA MÃO DE DEUS E VAI'),
  const Music(cipher: 'O ESPÍRITO DO SENHOR SEMPRE TE REVESTIRÁ'),
  const Music(cipher: 'SEGURA NA MÃO DE DEUS E VAI'),
  const Music(cipher: 'JESUS CRISTO PROMETEU QUE JAMAIS TE DEIXARÁ'),
  const Music(cipher: 'SEGURA NA MÃO DE DEUS E VAI'),
]);

Chant oracaoPelaFamilia =
    Chant(title: 'Oração pela família', category: 'Encerramento', ciphers: [
  const Music(cipher: 'D A'),
  const Music(cipher: 'QUE NENHUMA FAMÍLIA COMECE EM QUALQUER DE REPENTE'),
  const Music(cipher: 'G A D D4 D'),
  const Music(cipher: 'QUE NENHUMA FAMÍLIA TERMINE POR FALTA DE AMOR'),
  const Music(cipher: 'A'),
  const Music(cipher: 'QUE O CASAL SEJA UM PARA O OUTRO DE CORPO E DE MENTE'),
  const Music(cipher: 'Em G D D4 D'),
  const Music(cipher: 'E QUE NADA NO MUNDO SEPARE UM CASAL SONHADOR!'),
  const Music(cipher: 'QUE NENHUMA FAMÍLIA SE ABRIGUE DEBAIXO DA PONTE'),
  const Music(cipher: 'QUE NINGUÉM INTERFIRA NO LAR E NA VIDA DOS DOIS'),
  const Music(cipher: 'QUE NINGUÉM OS OBRIGUE A VIVER SEM NENHUM HORIZONTE'),
  const Music(
      cipher: 'QUE ELES VIVAM DO ONTEM, DO HOJE, E EM FUNÇÃO DE UM DEPOIS!'),
  const Music(cipher: 'D D7 G'),
  const Music(cipher: 'QUE A FAMÍLIA COMECE E TERMINE SABENDO ONDE VAI'),
  const Music(cipher: 'A D'),
  const Music(cipher: 'E QUE O HOMEM CARREGUE NOS OMBROS A GRAÇA DE UM PAI'),
  const Music(cipher: 'D7 G'),
  const Music(cipher: 'QUE A MULHER SEJA UM CÉU DE TERNURA, ACONCHEGO E CALOR'),
  const Music(cipher: 'D Em A D'),
  const Music(cipher: 'E QUE OS FILHOS CONHEÇAM A FORÇA QUE BROTA DO AMOR!'),
  const Music(cipher: 'D A7'),
  const Music(cipher: 'ABENÇOA, SENHOR, AS FAMÍLIAS! AMÉM!'),
  const Music(cipher: 'Em A D'),
  const Music(cipher: 'ABENÇOA, SENHOR, A MINHA TAMBÉM (BIS)'),
  const Music(cipher: 'QUE MARIDO E MULHER TENHAM FORÇA DE AMAR SEM MEDIDA'),
  const Music(cipher: 'QUE NINGUÉM VÁ DORMIR SEM PEDIR OU SEM DAR SEU PERDÃO'),
  const Music(cipher: 'QUE AS CRIANÇAS APRENDAM NO COLO, O SENTIDO DA VIDA'),
  const Music(cipher: 'QUE A FAMÍLIA CELEBRE A PARTILHA DO ABRAÇO E DO PÃO!'),
  const Music(
      cipher: 'QUE MARIDO E MULHER NÃO SE TRAIAM, NEM TRAIAM SEUS FILHOS!'),
  const Music(cipher: 'QUE O CIÚME NÃO MATE A CERTEZA DO AMOR ENTRE OS DOIS!'),
  const Music(cipher: 'QUE NO SEU FIRMAMENTO A ESTRELA QUE TEM MAIOR BRILHO,'),
  const Music(cipher: 'SEJA A FIRME ESPERANÇA DE UM CÉU AQUI MESMO E DEPOIS!'),
]);

Chant facoNovasTodasasCoisas = Chant(
    title: 'Faço novas todas as coisas',
    category: 'Encerramento',
    ciphers: [
      const Music(cipher: 'G C9'),
      const Music(cipher: 'EIS QUE FAÇO NOVAS TODAS AS COISAS,'),
      const Music(cipher: 'G'),
      const Music(cipher: 'QUE FAÇO NOVAS TODAS AS COISAS,'),
      const Music(cipher: 'C9'),
      const Music(cipher: 'QUE FAÇO NOVAS TODAS AS COISAS (2X)'),
      const Music(cipher: 'G C9'),
      const Music(
          cipher: 'É VIDA QUE BROTA DA VIDA, É FRUTO QUE CRESCE DO AMOR,'),
      const Music(cipher: 'G C9'),
      const Music(
          cipher: 'É VIDA QUE VENCE A MORTE, É VIDA QUE VEM DO SENHOR (2X)'),
      const Music(cipher: 'DEIXEI O SEPULCRO VAZIO, A MORTE NÃO ME SEGUROU.'),
      const Music(
          cipher: 'A PEDRA QUE ENTÃO ME PRENDIA NO TERCEIRO DIA ROLOU (2X)'),
      const Music(cipher: 'EU HOJE LHE DOU VIDA NOVA, RENOVO EM TI O AMOR.'),
      const Music(
          cipher:
              'LHE DOU UMA NOVA ESPERANÇA, TUDO O QUE ERA VELHO PASSOU (2X)'),
    ]);

Chant mariaDeNazare =
    Chant(title: 'Maria de Nazaré', category: 'Encerramento', ciphers: [
  const Music(cipher: 'E A B7 E'),
  const Music(cipher: 'MARIA DE NAZARÉ, MARIA ME CATIVOU,'),
  const Music(cipher: 'E A B7 E'),
  const Music(cipher: 'FEZ MAIS FORTE A MINHA FÉ, E POR FILHO ME ADOTOU.'),
  const Music(cipher: 'E7 A Am E'),
  const Music(
      cipher:
          'ÀS VEZES EU PARO E FICO A PENSAR E SEM PERCEBER ME VEJO A REZAR.'),
  const Music(cipher: 'C#m F#m B7 E'),
  const Music(cipher: 'E MEU CORAÇÃO SE PÕE A CANTAR, PRA VIRGEM DE NAZARÉ.'),
  const Music(cipher: 'E7 A Am E'),
  const Music(
      cipher: 'MENINA QUE DEUS AMOU E ESCOLHEU, PRA MÃE DE JESUS, O FILHO DE'),
  const Music(cipher: 'DEUS.'),
  const Music(cipher: 'C#m F#m B7 E'),
  const Music(cipher: 'MARIA QUE O POVO INTEIRO ELEGEU, SENHORA E MÃE DO CÉU.'),
  const Music(cipher: 'E7 A B7 E A B7 E'),
  const Music(cipher: 'AVE MARIA, AVE MARIA, AVE MARIA, MÃE DE JESUS (2X)'),
  const Music(cipher: 'MARIA QUE EU QUERO BEM, MARIA DO PURO AMOR'),
  const Music(cipher: 'IGUAL A VOCÊ, NINGUÉM'),
  const Music(cipher: 'MÃE PURA DO MEU SENHOR'),
  const Music(cipher: 'EM CADA MULHER QUE A TERRA CRIOU'),
  const Music(cipher: 'UM TRAÇO DE DEUS MARIA DEIXOU'),
  const Music(cipher: 'UM SONHO DE MÃE MARIA PLANTOU'),
  const Music(cipher: 'PRO MUNDO ENCONTRAR A PAZ'),
  const Music(cipher: 'MARIA QUE FEZ O CRISTO FALAR'),
  const Music(cipher: 'MARIA QUE FEZ JESUS CAMINHAR'),
  const Music(cipher: 'MARIA QUE SÓ VIVEU PRA SEU DEUS'),
  const Music(cipher: 'MARIA DO POVO MEU.'),
]);

Chant santaMaeMaria =
    Chant(title: 'Santa Mãe Maria', category: 'Encerramento', ciphers: [
  const Music(cipher: 'A'),
  const Music(cipher: '1. SANTA MÃE MARIA, NESTA TRAVESSIA'),
  const Music(cipher: 'E7'),
  const Music(cipher: 'CUBRA-NOS TEU MANTO COR DE ANIL.'),
  const Music(cipher: 'GUARDA NOSSA VIDA, MÃE APARECIDA,'),
  const Music(cipher: 'A'),
  const Music(cipher: 'SANTA PADROEIRA DO BRASIL.'),
  const Music(cipher: 'A Bm A/C# D E F#m E/G# A A G#m F#m E7 D A/C# Bm A'),
  const Music(cipher: 'A VE, MARI A! A VE, MARI A! (2X)'),
  const Music(cipher: '2. COM AMOR DIVINO GUARDA OS PEREGRINOS'),
  const Music(cipher: 'NESTA CAMINHADA PARA O ALÉM'),
  const Music(cipher: 'DÁ-LHES COMPANHIA, POIS TAMBÉM UM DIA'),
  const Music(cipher: 'FOSTE PEREGRINA EM BELÉM'),
  const Music(cipher: '3. MULHER PEREGRINA, FORÇA FEMININA'),
  const Music(cipher: 'A MAIS IMPORTANTE QUE EXISTIU'),
  const Music(cipher: 'COM JUSTIÇA QUERES QUE NOSSAS MULHERES'),
  const Music(cipher: 'SEJAM CONSTRUTORAS DO BRASIL'),
  const Music(cipher: '4. COM SEUS PASSOS LENTOS ENFRENTANDO OS VENTOS'),
  const Music(cipher: 'QUANDO SOPRAM NOUTRA DIREÇÃO'),
  const Music(cipher: 'TODA A MÃE IGREJA PEDE QUE TU SEJAS'),
  const Music(cipher: 'COMPANHEIRA DE LIBERTAÇÃO'),
]);
