import 'package:diasguto/models/chant.dart';
import 'package:diasguto/templates/cipher.dart';

List<Chant> offers = [
  aTiMeUDEUS,
  minhaVidaTemSentido,
  estarEmTuasMaos,
  seBendito,
  deMaosEstendidas,
  sabesSenhor,
  meuCoracaoEParaTi,
  umCoracaoParaAmar,
  teuSou,
  servoPorAmor,
  paoEVinho,
  dianteDoAltar,
  sobeAJerusalem,
];

Chant aTiMeUDEUS = Chant(
    title: 'A ti, Meu Deus',
    category: 'Ofertório',
    lyrics: [
      const Music(cipher: '1. A Ti, meu Deus elevo meu coração'),
      const Music(cipher: 'Elevo as minhas mãos'),
      const Music(cipher: 'Meu olhar, minha voz'),
      const Music(cipher: 'A Ti, meu Deus'),
      const Music(cipher: 'Eu quero oferecer'),
      const Music(cipher: 'Meus passos e meu viver'),
      const Music(cipher: 'Meus caminhos, meu sofrer'),
      verse(),
      const Refrao(cipher: 'A Tua ternura, Senhor, vem me abraçar'),
      const Refrao(cipher: 'E a Tua bondade infinita me perdoar'),
      const Refrao(cipher: 'Vou ser o Teu seguidor'),
      const Refrao(cipher: 'E Te dar o meu coração'),
      const Refrao(cipher: 'Eu quero sentir o calor, de Tuas mãos'),
      verse(),
      const Music(cipher: '2. A ti, meu Deus'),
      const Music(cipher: 'Que és bom e que tens amor'),
      const Music(cipher: 'Ao pobre, ao sofredor'),
      const Music(cipher: 'Vos servir, esperar'),
      const Music(cipher: 'Em ti Senhor'),
      const Music(cipher: 'Humildes se alegrarão'),
      const Music(cipher: 'Cantando a nossa canção'),
      const Music(cipher: 'De esperança e de paz'),
      verse(),
      const Refrao(cipher: 'A Tua ternura, Senhor, vem me abraçar'),
      const Refrao(cipher: 'E a Tua bondade infinita me perdoar'),
      const Refrao(cipher: 'Vou ser o Teu seguidor'),
      const Refrao(cipher: 'E Te dar o meu coração'),
      const Refrao(cipher: 'Eu quero sentir o calor, de Tuas mãos'),
    ],
    hasCypher: false);

Chant minhaVidaTemSentido = Chant(
    title: 'Minha vida tem sentido',
    category: 'Ofertório',
    lyrics: [
      const Music(
          cipher: 'Minha vida tem sentido, cada vez que eu venho aqui,'),
      const Music(cipher: 'E te faço o meu pedido de não me esquecer de ti.'),
      verse(),
      const Music(cipher: 'Meu amor é como este pão, que era trigo,'),
      const Music(cipher: 'Que alguém plantou depois colheu.'),
      const Music(cipher: 'E depois, tornou-se salvação'),
      const Music(cipher: 'E deu mais vida e alimentou o povo meu.'),
      verse(),
      const Music(cipher: 'Eu te ofereço este pão,'),
      const Music(cipher: 'Eu te ofereço meu amor. (bis)'),
      verse(),
      const Music(
          cipher: 'Minha vida tem sentido, cada vez que eu venho aqui,'),
      const Music(cipher: 'E te faço o meu pedido de não me esquecer de ti.'),
      verse(),
      const Music(cipher: 'Meu amor é como este vinho, que era fruto,'),
      const Music(cipher: 'Que alguém plantou, depois colheu.'),
      const Music(cipher: 'E depois encheu-se de carinho,'),
      const Music(cipher: 'E deu mais vida, e saciou o povo meu.'),
      verse(),
      const Music(cipher: 'Eu te ofereço vinho e pão,'),
      const Music(cipher: 'Eu te ofereço meu amor. (bis)'),
    ],
    hasCypher: false);

Chant estarEmTuasMaos = Chant(
    title: 'Estar em tuas Mãos',
    category: 'Ofertório',
    lyrics: [
      const Music(cipher: 'Mão na terra e o coração além deste céu'),
      const Music(cipher: 'E a semente que brota é um germe de eternidade'),
      const Music(cipher: 'Vai brotando, crescendo, esperando'),
      const Music(cipher: 'É a vida que vem despontar'),
      const Music(cipher: 'E este trigo maduro, a colheita o recolherá'),
      const Music(cipher: ' '),
      const Music(cipher: 'Estar em tuas mãos, ó Pai'),
      const Music(cipher: 'E a vida ofertar'),
      const Music(cipher: 'No pão e no vinho a Ti'),
      const Music(cipher: 'E o céu se abrirá'),
      const Music(cipher: 'Estar em tuas mãos, Senhor'),
      const Music(cipher: 'E a vida entregar'),
      const Music(cipher: 'A minha oblação em Ti'),
      const Music(cipher: 'Se perderá, frutificará'),
      const Music(cipher: 'Frutificará, frutificará, frutificará!'),
      const Music(cipher: ' '),
      const Music(cipher: 'Da videira a flor não restará, passará'),
      const Music(cipher: 'E o fruto da terra surgirá, brotará'),
      const Music(cipher: 'Pela força do vento, da chuva'),
      const Music(cipher: 'E do sol que traz vida e calor'),
      const Music(cipher: 'Cada dia, crescendo e aprendendo a recomeçar'),
    ],
    hasCypher: false);

Chant seBendito = Chant(
    title: 'Sê bendito',
    category: 'Ofertório',
    lyrics: [
      const Music(cipher: 'Sê bendito, Senhor, para sempre'),
      const Music(cipher: 'Pelos frutos das nossas jornadas!'),
      const Music(cipher: 'Repartidos na mesa do reino'),
      const Music(cipher: 'Anunciam a paz almejada!'),
      verse(),
      const Refrao(cipher: 'Senhor da vida,'),
      const Refrao(cipher: 'Tu és a nossa salvação!'),
      const Refrao(cipher: 'Ao prepararmos a tua mesa'),
      const Refrao(cipher: 'Em ti buscamos ressurreição!'),
      verse(),
      const Music(cipher: 'Sê bendito, Senhor, para sempre'),
      const Music(cipher: 'Pelos mares, os rios e as fontes!'),
      const Music(cipher: 'Nos recordam a tua justiça'),
      const Music(cipher: 'Que nos leva a um novo horizonte!'),
      verse(),
      const Refrao(cipher: 'Senhor da vida,'),
      const Refrao(cipher: 'Tu és a nossa salvação!'),
      const Refrao(cipher: 'Ao prepararmos a tua mesa'),
      const Refrao(cipher: 'Em ti buscamos ressurreição!'),
      verse(),
      const Music(cipher: 'Sê bendito, Senhor, para sempre'),
      const Music(cipher: 'Pelas bênçãos qual chuva torrente!'),
      const Music(cipher: 'Tu fecundas o chão desta vida'),
      const Music(cipher: 'Que abriga uma nova semente.'),
      verse(),
      const Refrao(cipher: 'Senhor da vida,'),
      const Refrao(cipher: 'Tu és a nossa salvação!'),
      const Refrao(cipher: 'Ao prepararmos a tua mesa'),
      const Refrao(cipher: 'Em ti buscamos ressurreição!'),
    ],
    hasCypher: false);

Chant deMaosEstendidas = Chant(
    title: 'De Mãos estendidas',
    category: 'Ofertório',
    lyrics: [
      const Refrao(cipher: 'De mãos estendidas'),
      const Refrao(cipher: 'Ofertamos o que de graça recebemos (bis)'),
      verse(),
      const Music(cipher: 'A natureza tão bela'),
      const Music(cipher: 'Que é louvor, que é serviço'),
      const Music(cipher: 'O Sol que ilumina as trevas'),
      const Music(cipher: 'Transformando-as em luz'),
      verse(),
      const Music(cipher: 'O dia que nos traz o pão'),
      const Music(cipher: 'E a noite que nos dá repouso'),
      const Music(cipher: 'Ofertemos ao senhor'),
      const Music(cipher: 'O louvor da criação'),
      verse(),
      const Refrao(cipher: 'De mãos estendidas'),
      const Refrao(cipher: 'Ofertamos o que de graça recebemos (bis)'),
      verse(),
      const Music(cipher: 'Nossa vida toda inteira'),
      const Music(cipher: 'Ofertamos ao Senhor'),
      const Music(cipher: 'Como prova de amizade'),
      const Music(cipher: 'Como prova de amor'),
      verse(),
      const Music(cipher: 'Com o vinho e com o pão'),
      const Music(cipher: 'Ofertamos ao Senhor'),
      const Music(cipher: 'Nossa vida toda inteira'),
      const Music(cipher: 'O louvor da criação'),
      verse(),
      const Refrao(cipher: 'De mãos estendidas'),
      const Refrao(cipher: 'Ofertamos o que de graça recebemos (bis)'),
    ],
    hasCypher: false);

Chant sabesSenhor = Chant(
    title: 'Sabes, Senhor',
    category: 'Ofertório',
    lyrics: [
      const Refrao(cipher: 'Sabes, senhor'),
      const Refrao(cipher: 'O que temos é tão pouco pra dar'),
      const Refrao(cipher: 'Mas esse pouco'),
      const Refrao(cipher: 'Nós queremos com os irmãos compartilhar'),
      verse(),
      const Music(cipher: 'Queremos nesta hora'),
      const Music(cipher: 'Diante dos irmãos'),
      const Music(cipher: 'Comprometer a vida'),
      const Music(cipher: 'Buscando a união'),
      verse(),
      const Refrao(cipher: 'Sabes, senhor'),
      const Refrao(cipher: 'O que temos é tão pouco pra dar'),
      const Refrao(cipher: 'Mas esse pouco'),
      const Refrao(cipher: 'Nós queremos com os irmãos compartilhar'),
      verse(),
      const Music(cipher: 'Sabemos que é difícil'),
      const Music(cipher: 'Os bens compartilhar'),
      const Music(cipher: 'Mas com a tua graça'),
      const Music(cipher: 'Senhor, podemos dar'),
      verse(),
      const Refrao(cipher: 'Sabes, senhor'),
      const Refrao(cipher: 'O que temos é tão pouco pra dar'),
      const Refrao(cipher: 'Mas esse pouco'),
      const Refrao(cipher: 'Nós queremos com os irmãos compartilhar'),
      verse(),
      const Music(cipher: 'Olhando o teu exemplo'),
      const Music(cipher: 'Senhor, vamos seguir'),
      const Music(cipher: 'Fazendo o bem a todos'),
      const Music(cipher: 'Sem nada exigir'),
      verse(),
      const Refrao(cipher: 'Sabes, senhor'),
      const Refrao(cipher: 'O que temos é tão pouco pra dar'),
      const Refrao(cipher: 'Mas esse pouco'),
      const Refrao(cipher: 'Nós queremos com os irmãos compartilhar'),
      verse(),
    ],
    hasCypher: false);

Chant meuCoracaoEParaTi = Chant(
    title: 'Meu coração é para ti',
    category: 'Ofertório',
    lyrics: [
      const Music(cipher: '1. Meu coração é para Ti, Senhor'),
      const Music(cipher: 'Meu coração é para Ti, Senhor'),
      const Music(cipher: 'Meu coração é para Ti, Senhor'),
      const Music(cipher: 'Meu coração é para Ti'),
      verse(),
      const Refrao(cipher: 'Porque Tu me deste a vida'),
      const Refrao(cipher: 'Porque Tu me deste o existir'),
      const Refrao(cipher: 'Porque Tu me deste o carinho'),
      const Refrao(cipher: 'Me deste o amor (bis)'),
      verse(),
      const Music(cipher: '2. A minha vida é para Ti, Senhor'),
      const Music(cipher: 'O meu trabalho é para Ti, Senhor'),
      const Music(cipher: 'A minha casa é para Ti, Senhor'),
      const Music(cipher: 'A minha vida é para Ti'),
      verse(),
      const Refrao(cipher: 'Porque Tu me deste a vida'),
      const Refrao(cipher: 'Porque Tu me deste o existir'),
      const Refrao(cipher: 'Porque Tu me deste o carinho'),
      const Refrao(cipher: 'Me deste o amor (bis)'),
      verse(),
      const Music(cipher: '3. Pão e vinho são para Ti, Senhor'),
      const Music(cipher: 'Pão e vinho são para Ti, Senhor'),
      const Music(cipher: 'Pão e vinho são para Ti, Senhor'),
      const Music(cipher: 'Pão e vinho são para Ti, Senhor'),
      verse(),
      const Refrao(cipher: 'Porque Tu me deste a vida'),
      const Refrao(cipher: 'Porque Tu me deste o existir'),
      const Refrao(cipher: 'Porque Tu me deste o carinho'),
      const Refrao(cipher: 'Me deste o amor (bis)'),
    ],
    hasCypher: false);

Chant umCoracaoParaAmar = Chant(
    title: 'Um coração para amar',
    category: 'Ofertório',
    lyrics: [
      const Music(cipher: '1. Um coração para amar, pra perdoar e sentir'),
      const Music(cipher: 'Para chorar e sorrir, ao me criar tu me destes'),
      const Music(cipher: 'Um coração pra sonhar, inquieto e sempre a bater'),
      const Music(cipher: 'Ansioso por entender as coisas que tu disseste'),
      verse(),
      const Refrao(cipher: 'Eis o que eu venho te dar'),
      const Refrao(cipher: 'Eis o que eu ponho no altar'),
      const Refrao(cipher: 'Toma, Senhor, que ele é teu'),
      const Refrao(cipher: 'Meu coração não é meu (bis)'),
      verse(),
      const Music(cipher: '2. Quero que o meu coração seja tão cheio de paz'),
      const Music(cipher: 'Que não se sinta capaz de sentir ódio ou rancor'),
      const Music(cipher: 'Quero que a minha oração possa me amadurecer'),
      const Music(cipher: 'Leve-me a compreender as consequências do amor'),
      verse(),
      const Refrao(cipher: 'Eis o que eu venho te dar'),
      const Refrao(cipher: 'Eis o que eu ponho no altar'),
      const Refrao(cipher: 'Toma, Senhor, que ele é teu'),
      const Refrao(cipher: 'Meu coração não é meu (bis)'),
    ],
    hasCypher: false);

Chant teuSou = Chant(
    title: 'Teu sou',
    category: 'Ofertório',
    lyrics: [
      const Music(cipher: '1. Eu não sou nada e do pó nasci,'),
      const Music(cipher: 'Mas Tu me amas e morrestes por mim'),
      const Music(cipher: 'Diante da cruz só posso exclamar'),
      const Music(cipher: 'Teu sou, Teu sou.'),
      verse(),
      const Refrao(cipher: 'Toma minhas mãos te peço'),
      const Refrao(cipher: 'Toma meus lábios, te amo'),
      const Refrao(cipher: 'Toma minha vida, ó Pai Teu sou.'),
      verse(),
      const Music(cipher: '2. Quando de joelhos te olho, ó Jesus'),
      const Music(cipher: 'Vejo tua grandeza e minha pequenês'),
      const Music(cipher: 'Que posso dar-te eu? Só meu ser'),
      const Music(cipher: 'Teu sou, teu sou.'),
      verse(),
      const Refrao(cipher: 'Toma minhas mãos te peço'),
      const Refrao(cipher: 'Toma meus lábios, te amo'),
      const Refrao(cipher: 'Toma minha vida, ó Pai Teu sou.'),
      verse(),
    ],
    hasCypher: false);

Chant servoPorAmor = Chant(
    title: 'Servo por amor',
    category: 'Ofertório',
    lyrics: [
      const Music(cipher: '1. Numa noite de fadiga, sobre o barco em alto mar'),
      const Music(cipher: 'O céu começa a clarear, a tua rede está vazia'),
      const Music(cipher: 'Mas a voz que te chama, te mostrará um outro mar'),
      const Music(cipher: 'E sobre muitos corações a tua rede lançarás'),
      verse(),
      const Refrao(cipher: 'Doa a tua vida, como Maria aos pés da cruz'),
      const Refrao(cipher: 'E serás servo de cada homem'),
      const Refrao(cipher: 'Servo por amor'),
      const Refrao(cipher: 'Sacerdote da humanidade'),
      verse(),
      const Music(cipher: '2. Caminhavas no silêncio, esperando além da dor'),
      const Music(cipher: 'Que a semente que tu lançavas'),
      const Music(cipher: 'No bom terreno germinasse'),
      const Music(cipher: 'Mas o coração exulta'),
      const Music(cipher: 'Porque o campo já está dourado'),
      const Music(cipher: 'O grão maduro pelo sol, no celeiro pode entrar.'),
      verse(),
      const Refrao(cipher: 'Doa a tua vida, como Maria aos pés da cruz'),
      const Refrao(cipher: 'E serás servo de cada homem'),
      const Refrao(cipher: 'Servo por amor'),
      const Refrao(cipher: 'Sacerdote da humanidade'),
    ],
    hasCypher: false);

Chant paoEVinho = Chant(
    title: 'Pão e Vinho',
    category: 'Ofertório',
    lyrics: [
      const Music(cipher: 'Pão e vinho te apresentamos nesse altar'),
      const Music(cipher: 'Como sinal que tu recolhes nossa oferta'),
      const Music(cipher: 'Tudo o que somos deixamos aqui. (bis)'),
      verse(),
      const Music(cipher: 'É um milagre que se dá'),
      const Music(cipher: 'O pão e o vinho em corpo e sangue,'),
      const Music(cipher: 'Vão se transformar'),
      const Music(cipher: 'Não há limites para o amor'),
      const Music(cipher: 'Vem transformar também minha vida'),
      const Music(cipher: 'Ó senhor, é teu esse milagre de amor. (bis)'),
    ],
    hasCypher: false);

Chant dianteDoAltar = Chant(
    title: 'Diante do altar',
    category: 'Ofertório',
    lyrics: [
      const Music(
          cipher: '1. Os grãos que formam espigas se unem pra serem pão'),
      const Music(cipher: 'Os homens que são Igreja se unem pela oblação.'),
      verse(),
      const Refrao(cipher: 'Diante do altar, Senhor, entendo minha vocação'),
      const Refrao(cipher: 'Devo sacrificar a vida por meus irmãos (bis)'),
      verse(),
      const Music(cipher: '2. O grão caído na terra só vive se vai morrer'),
      const Music(cipher: 'É dando que se recebe, morrendo se vai viver.'),
      verse(),
      const Refrao(cipher: 'Diante do altar, Senhor, entendo minha vocação'),
      const Refrao(cipher: 'Devo sacrificar a vida por meus irmãos (bis)'),
      verse(),
      const Music(
          cipher: '3. O vinho e o pão ofertamos, são nossas respostas de amor'),
      const Music(cipher: 'Pedimos humildemente, aceita-nos, ó Senhor.'),
      verse(),
      const Refrao(cipher: 'Diante do altar, Senhor, entendo minha vocação'),
      const Refrao(cipher: 'Devo sacrificar a vida por meus irmãos (bis)'),
    ],
    hasCypher: false);

Chant sobeAJerusalem = Chant(
    title: 'Sobe à Jerusalém',
    category: 'Ofertório',
    lyrics: [
      const Music(cipher: 'Sobe a Jerusalém, Virgem oferente sem igual'),
      const Music(
          cipher: 'Vai, apresenta ao Pai, teu Menino: luz que chegou no Natal'),
      const Music(cipher: 'E, junto à sua cruz, quando Deus morrer fica de pé'),
      const Music(
          cipher: 'Sim, Ele te salvou, mas o ofereceste por nós com toda fé'),
      verse(),
      const Music(cipher: 'Nós vamos renovar este sacrifício de Jesus'),
      const Music(
          cipher:
              'Morte e ressurreição, vida que brotou de sua oferta na cruz'),
      const Music(cipher: 'Mãe, vem nos ensinar a fazer da vida uma oblação'),
      const Music(
          cipher: 'Culto agradável a Deus é fazer a oferta do próprio coração'),
    ],
    hasCypher: false);
