import 'package:diasguto/models/chant.dart';
import 'package:diasguto/templates/cipher.dart';

List<Chant> posComunion = [
  estasEntreNos,
  teLouvoEmVerdade,
  amarComoJesusAmou,
  qualAChave,
  soPorTiJesus,
  noitesTraicoeiras,
  ninguemTeAma,
  alfaOmega,
  tudoEDoPai,
  amarTeMais
];

Chant estasEntreNos = Chant(
    title: 'Estás entre nós',
    category: 'Pós Comunhão',
    lyrics: [
      const Music(
          cipher:
              '1. Tu és minha vida, outro Deus não há. Tu és minha estrada, a minha verdade. Em tua Palavra eu caminharei, enquanto eu viver e até quando tu quiseres. Já não sentirei temor, pois estás aqui, tu estás no meio de nós'),
      verse(),
      const Music(cipher: '2. Creio em ti, Senhor, vindo de Maria,'),
      const Music(cipher: 'Filho eterno e Santo, homem como nós.'),
      const Music(
          cipher:
              'Tu morreste por amor, vivo estás em nós, Unidade Trina com o Espirito e o Pai. E um dia eu bem sei, tu retornarás, e abrirás o Reino dos Céus!'),
      verse(),
      const Music(
          cipher:
              '3. Tu és minha força, outro Deus não há, tu és minha paz, minha liberdade.'),
      const Music(
          cipher:
              'Nada nessa vida nos separará, em tuas mãos seguras minha vida guardarás. Eu não temerei o mal, tu me livrarás, e no teu perdão viverei!'),
      verse(),
      const Music(
          cipher:
              '4. Ó Senhor da vida, creio sempre em ti! Filho Salvador, eu espero em ti! Santo Espírito de Amor, desce sobre nós. Tu de mil caminhos nos conduzes a uma fé, e por mil estradas onde andarmos nós, qual semente nos levarás!'),
    ],
    hasCypher: false,
    ciphers: []);

Chant teLouvoEmVerdade = Chant(
    title: 'Te louvo em verdade',
    category: 'Pós Comunhão',
    lyrics: [
      const Music(cipher: '1. Mesmo na tempestade,'),
      const Music(cipher: 'mesmo que se agite o mar,'),
      const Music(cipher: 'te louvo, te louvo em verdade.'),
      verse(),
      Music(cipher: '2. Mesmo longe dos meus,'),
      const Music(cipher: 'mesmo na solidão te louvo,'),
      const Music(cipher: 'te louvo em verdade.'),
      verse(),
      const Refrao(cipher: 'Pois somente tenho a Ti'),
      const Refrao(cipher: 'Tu és a minha herança.'),
      const Refrao(cipher: 'Te louvo, te louvo em verdade.'),
      verse(),
      const Music(cipher: '3. Mesmo que me faltem as palavras'),
      const Music(cipher: 'mesmo que eu não saiba louvar. T'),
      const Music(cipher: 'e louvo, te louvo em verdade.'),
      verse(),
      const Refrao(cipher: 'Pois somente tenho a Ti'),
      const Refrao(cipher: 'Tu és a minha herança.'),
      const Refrao(cipher: 'Te louvo, te louvo em verdade.'),
      verse(),
    ],
    hasCypher: false,
    ciphers: []);

Chant amarComoJesusAmou = Chant(
    title: 'Amar como Jesus amou',
    category: 'Pós Comunhão',
    lyrics: [
      const Music(cipher: '1. Um dia uma criança me parou'),
      const Music(cipher: 'olhou-me nos meus olhos a sorrir,'),
      const Music(cipher: 'caneta e papel na sua mão,'),
      const Music(cipher: 'tarefa escolar para cumprir'),
      const Music(cipher: 'e perguntou no meio de um sorriso'),
      const Music(cipher: 'o que é preciso para ser feliz.'),
      verse(),
      const Refrao(cipher: 'Amar como Jesus amou,'),
      const Refrao(cipher: 'sonhar como Jesus sonhou,'),
      const Refrao(cipher: 'pensar como Jesus pensou'),
      const Refrao(cipher: 'viver como Jesus viveu'),
      verse(),
      const Refrao(cipher: 'Sentir o que Jesus sentia'),
      const Refrao(cipher: 'sorrir como Jesus sorria'),
      const Refrao(cipher: 'e ao chegar ao fim do dia'),
      const Refrao(cipher: 'eu sei que eu dormiria muito mais feliz.(Bis)'),
      verse(),
      const Music(cipher: '2. Olhando o que eu falei ela me olhou'),
      const Music(cipher: 'e disse que era lindo o que eu falei'),
      const Music(cipher: 'pediu que repetisse por favor'),
      const Music(cipher: 'mas não falasse tudo de uma vez.'),
      const Music(cipher: 'E perguntou no meio de um sorriso'),
      const Music(cipher: 'o que é preciso para ser feliz.'),
      verse(),
      const Refrao(cipher: 'Amar como Jesus amou,'),
      const Refrao(cipher: 'sonhar como Jesus sonhou,'),
      const Refrao(cipher: 'pensar como Jesus pensou'),
      const Refrao(cipher: 'viver como Jesus viveu'),
      verse(),
      const Refrao(cipher: 'Sentir o que Jesus sentia'),
      const Refrao(cipher: 'sorrir como Jesus sorria'),
      const Refrao(cipher: 'e ao chegar ao fim do dia'),
      const Refrao(cipher: 'eu sei que eu dormiria muito mais feliz.(Bis)'),
      verse(),
      const Music(cipher: '3. Depois que eu terminei de repetir'),
      const Music(cipher: 'seus olhos não saíram do papel.'),
      const Music(cipher: 'Toquei no seu rostinho e a sorrir'),
      const Music(cipher: 'pedi que ao transmitir fosse fiel.'),
      const Music(cipher: 'E ela deu-me um beijo demorado'),
      const Music(cipher: 'e ao meu lado foi dizendo assim'),
      verse(),
      const Refrao(cipher: 'Amar como Jesus amou,'),
      const Refrao(cipher: 'sonhar como Jesus sonhou,'),
      const Refrao(cipher: 'pensar como Jesus pensou'),
      const Refrao(cipher: 'viver como Jesus viveu'),
      verse(),
      const Refrao(cipher: 'Sentir o que Jesus sentia'),
      const Refrao(cipher: 'sorrir como Jesus sorria'),
      const Refrao(cipher: 'e ao chegar ao fim do dia'),
      const Refrao(cipher: 'eu sei que eu dormiria muito mais feliz.(Bis)'),
      verse(),
    ],
    hasCypher: true,
    ciphers: [
      const Music(cipher: 'Tom: Eb'),
      const Cifra(cipher: 'Eb                       Bb7'),
      const Music(cipher: 'Um dia uma criança me parou'),
      const Cifra(cipher: '                              Eb'),
      const Music(cipher: 'Olhou-me nos meus olhos a sorrir'),
      const Cifra(cipher: '                       Bb7'),
      const Music(cipher: 'Caneta e papel na sua mão'),
      const Cifra(cipher: '                         Eb'),
      const Music(cipher: 'Tarefa escolar para cumprir'),
      const Cifra(cipher: '   Eb7                        Ab'),
      const Music(cipher: 'E perguntou no meio de um sorriso'),
      const Cifra(cipher: '            Eb        Bb7    Eb'),
      const Music(cipher: 'O que é preciso para ser  feliz?'),
      verse(),
      const Cifra(cipher: '  Eb7             Ab'),
      const Music(cipher: 'Amar como Jesus amou'),
      const Cifra(cipher: '    Bb7               Eb'),
      const Music(cipher: 'Sonhar como Jesus sonhou'),
      const Cifra(cipher: '    Cm7               Bb7'),
      const Music(cipher: 'Pensar como Jesus pensou'),
      const Cifra(cipher: '                    Eb'),
      const Music(cipher: 'Viver como Jesus viveu'),
      verse(),
      const Cifra(cipher: '    Eb7                Ab'),
      const Music(cipher: 'Sentir o que Jesus sentia'),
      const Cifra(cipher: '    Bb7               Gm7'),
      const Music(cipher: 'Sorrir como Jesus sorria'),
      const Cifra(cipher: '  Cm7                  Fm'),
      const Music(cipher: 'E ao chegar ao fim do dia'),
      const Cifra(cipher: '                 Bb7                 Eb'),
      const Music(cipher: 'Eu sei que dormiria muito mais feliz'),
      verse(),
      const Cifra(cipher: '    Eb7                Ab'),
      const Music(cipher: 'Sentir o que Jesus sentia'),
      const Cifra(cipher: '    Bb7               Gm7'),
      const Music(cipher: 'Sorrir como Jesus sorria'),
      const Cifra(cipher: '  Cm7                  Fm'),
      const Music(cipher: 'E ao chegar ao fim do dia'),
      const Cifra(cipher: '                 Bb7                 Eb'),
      const Music(cipher: 'Eu sei que dormiria muito mais feliz'),
      verse(),
      const Cifra(cipher: '   Eb                            Bb7'),
      const Music(cipher: 'Ouvindo o que eu falei ela me olhou'),
      const Cifra(cipher: '                                  Eb'),
      const Music(cipher: 'E disse que era lindo o que eu falei'),
      const Cifra(cipher: '                              Bb7'),
      const Music(cipher: 'Pediu que eu repetisse por favor'),
      const Cifra(cipher: '                             Eb'),
      const Music(cipher: 'Que não falasse tudo de uma vez'),
      const Cifra(cipher: '   Eb7                      Ab'),
      const Music(cipher: 'E perguntou de novo num sorriso'),
      const Cifra(cipher: '            Eb        Bb7     Eb'),
      const Music(cipher: 'O que é preciso para ser   feliz?'),
      verse(),
      const Cifra(cipher: '  Eb7             Ab'),
      const Music(cipher: 'Amar como Jesus amou'),
      const Cifra(cipher: '    Bb7               Eb'),
      const Music(cipher: 'Sonhar como Jesus sonhou'),
      const Cifra(cipher: '    Cm7               Bb7'),
      const Music(cipher: 'Pensar como Jesus pensou'),
      const Cifra(cipher: '                    Eb'),
      const Music(cipher: 'Viver como Jesus viveu'),
      verse(),
      const Cifra(cipher: '    Eb7                Ab'),
      const Music(cipher: 'Sentir o que Jesus sentia'),
      const Cifra(cipher: '    Bb7               Gm7'),
      const Music(cipher: 'Sorrir como Jesus sorria'),
      const Cifra(cipher: '  Cm7                  Fm'),
      const Music(cipher: 'E ao chegar ao fim do dia'),
      const Cifra(cipher: '                 Bb7                 Eb'),
      const Music(cipher: 'Eu sei que dormiria muito mais feliz'),
      verse(),
      const Cifra(cipher: '    Eb7                Ab'),
      const Music(cipher: 'Sentir o que Jesus sentia'),
      const Cifra(cipher: '    Bb7               Gm7'),
      const Music(cipher: 'Sorrir como Jesus sorria'),
      const Cifra(cipher: '  Cm7                  Fm'),
      const Music(cipher: 'E ao chegar ao fim do dia'),
      const Cifra(cipher: '                 Bb7                 Eb'),
      const Music(cipher: 'Eu sei que dormiria muito mais feliz'),
      verse(),
      const Cifra(cipher: '   Eb                          Bb7'),
      const Music(cipher: 'Depois que eu terminei de repetir'),
      const Cifra(cipher: '                           Eb'),
      const Music(cipher: 'Seus olhos não saíam do papel'),
      const Cifra(cipher: '                               Bb7'),
      const Music(cipher: 'Toquei no seu rostinho e a sorrir'),
      const Cifra(cipher: '                               Eb'),
      const Music(cipher: 'Pedi que ao transmitir fosse fiel'),
      const Cifra(cipher: '  Eb7                      Ab'),
      const Music(cipher: 'E ela deu-me um beijo demorado'),
      const Cifra(cipher: '          Eb         Bb7     Eb'),
      const Music(cipher: 'E ao meu lado foi dizendo assim'),
      verse(),
      const Cifra(cipher: '  Eb7             Ab'),
      const Music(cipher: 'Amar como Jesus amou'),
      const Cifra(cipher: '    Bb7               Eb'),
      const Music(cipher: 'Sonhar como Jesus sonhou'),
      const Cifra(cipher: '    Cm7               Bb7'),
      const Music(cipher: 'Pensar como Jesus pensou'),
      const Cifra(cipher: '                    Eb'),
      const Music(cipher: 'Viver como Jesus viveu'),
      verse(),
      const Cifra(cipher: '    Eb7                Ab'),
      const Music(cipher: 'Sentir o que Jesus sentia'),
      const Cifra(cipher: '    Bb7               Gm7'),
      const Music(cipher: 'Sorrir como Jesus sorria'),
      const Cifra(cipher: '  Cm7                  Fm'),
      const Music(cipher: 'E ao chegar ao fim do dia'),
      const Cifra(cipher: '                 Bb7                 Eb'),
      const Music(cipher: 'Eu sei que dormiria muito mais feliz'),
      verse(),
      const Cifra(cipher: '    Eb7                Ab'),
      const Music(cipher: 'Sentir o que Jesus sentia'),
      const Cifra(cipher: '    Bb7               Gm7'),
      const Music(cipher: 'Sorrir como Jesus sorria'),
      const Cifra(cipher: '  Cm7                  Fm'),
      const Music(cipher: 'E ao chegar ao fim do dia'),
      const Cifra(cipher: '                 Bb7                 Eb'),
      const Music(cipher: 'Eu sei que dormiria muito mais feliz'),
    ]);

Chant qualAChave = Chant(
    title: 'Qual é a chave',
    category: 'Pós Comunhão',
    lyrics: [
      const Music(cipher: 'Qual é a chave? Qual é o segredo'),
      const Music(cipher: 'Que abre as portas do teu coração (2x).'),
      verse(),
      const Music(cipher: 'Porque não falar se Ele quer te ouvir.'),
      const Music(cipher: 'Porque se esconder se Ele está aqui.'),
      const Music(cipher: 'Porque não aceitar se Ele quer te dar.'),
      const Music(cipher: 'Porque insistir em resistir,'),
      const Music(cipher: 'pois Ele tem tanto pra te falar.'),
      const Music(cipher: 'Quer te amar te perdoar,'),
      const Music(cipher: 'mas é você quem tem que abrir o coração.'),
      verse(),
      const Refrao(cipher: 'Deixa Jesus te consolar.'),
      const Refrao(cipher: 'Deixa Jesus Te abençoar.'),
      const Refrao(cipher: 'Deixa Jesus Te dar'),
      const Refrao(cipher: 'a tua salvação.'),
    ],
    hasCypher: false,
    ciphers: []);

Chant soPorTiJesus = Chant(
    title: 'Só por Ti, Jesus',
    category: 'Pós Comunhão',
    lyrics: [
      const Music(cipher: 'Só por ti Jesus, quero me consumir'),
      const Music(cipher: 'como vela que queima no altar'),
      const Music(cipher: 'me consumir de amor.'),
      verse(),
      const Music(cipher: 'Só por ti Jesus,'),
      const Music(cipher: 'quero me derramar,'),
      const Music(cipher: 'como rio se entrega ao mar,'),
      const Music(cipher: 'me derramar de amor.'),
      verse(),
      const Music(cipher: 'Pois tu és o meu amparo o meu refugio,'),
      const Music(cipher: "és a alegria de minh'alma,"),
      const Music(cipher: 'só em ti repousa a minha esperança,'),
      const Music(
          cipher: 'não vacilarei e mesmo na dor quero seguir, até o fim.'),
    ],
    hasCypher: false,
    ciphers: []);

Chant noitesTraicoeiras = Chant(
    title: 'Noites traiçoeiras',
    category: 'Pós Comunhão',
    lyrics: [
      const Music(cipher: '1. Deus está aqui neste momento,'),
      const Music(cipher: 'sua presença é real em meu viver.'),
      const Music(cipher: 'Entregue sua vida e seus problemas,'),
      const Music(cipher: 'Fale com Deus ele vai ajudar você.'),
      verse(),
      const Music(cipher: '2. Deus te trouxe aqui'),
      const Music(cipher: 'para aliviar o seu sofrimento.'),
      const Music(cipher: 'É ele o autor da fé, do principio ao fim'),
      const Music(cipher: 'de todo o seu tormento.'),
      verse(),
      const Music(cipher: 'E ainda se vier noite Traiçoeiras'),
      const Music(cipher: 'se a cruz pesada for'),
      const Music(cipher: 'Cristo estará Contigo'),
      const Music(cipher: 'e o mundo pode até'),
      const Music(cipher: 'fazer vocÊ chorar'),
      const Music(cipher: 'mas Deus te quer sorrindo.'),
      verse(),
      const Music(cipher: '3. Seja qual for o seu problema,'),
      const Music(cipher: 'fale com Deus ele vai ajudar você.'),
      const Music(cipher: 'Após a dor vem a alegria'),
      const Music(cipher: 'Deus amor é não te deixará sofrer.'),
    ],
    hasCypher: false,
    ciphers: []);

Chant ninguemTeAma = Chant(
    title: 'Ninguém te ama como eu',
    category: 'Pós Comunhão',
    lyrics: [
      const Music(cipher: 'Tenho esperado este momento,'),
      const Music(cipher: 'tenho esperado que viesses a mim.'),
      const Music(cipher: 'Tenho esperado que me fales,'),
      const Music(cipher: 'tenho esperado que estivesses assim.'),
      verse(),
      const Music(cipher: 'Eu sei bem o que tens vivido,'),
      const Music(cipher: 'sei também que tens chorado.'),
      const Music(cipher: 'Eu sei bem que tens sofrido,'),
      const Music(cipher: 'pois permaneço ao teu lado.'),
      verse(),
      const Refrao(cipher: 'Ninguém te ama como eu,'),
      const Refrao(cipher: 'Ninguém te ama como eu'),
      const Refrao(cipher: 'Olhe pra cruz esta é a minha grande prova.'),
      const Refrao(cipher: 'Ninguém te ama como eu.'),
      verse(),
      const Refrao(cipher: 'Ninguém te ama como eu.'),
      const Refrao(cipher: 'Ninguém te ama como eu'),
      const Refrao(cipher: 'olhe pra cruz foi por ti porque te amo,'),
      const Refrao(cipher: 'ninguém te ama como eu.'),
      verse(),
      const Music(cipher: 'Eu sei o que me dizes'),
      const Music(cipher: 'ainda que nunca me fales.'),
      const Music(cipher: 'Eu sei bem o que tens sentido'),
      const Music(cipher: 'ainda que nunca me reveles.'),
      const Music(cipher: 'Tenho andado ao teu lado,'),
      const Music(cipher: 'junto a ti permanecido.'),
      const Music(cipher: 'Eu te levo em meus braços,'),
      const Music(cipher: 'pois sou teu melhor amigo.'),
    ],
    hasCypher: false,
    ciphers: []);

Chant alfaOmega = Chant(
    title: 'Alfa, ômega',
    category: 'Pós Comunhão',
    lyrics: [
      const Music(cipher: 'Alfa, Omega, principio e fim,'),
      const Music(cipher: 'sim Ele é, sim ele é. (bis)'),
      verse(),
      const Music(cipher: 'Lírio dos vales,'),
      const Music(cipher: 'estrela da manhã'),
      const Music(cipher: 'para sempre cantarei o teu amor.'),
      verse(),
      const Music(cipher: 'A Ele a glória,'),
      const Music(cipher: 'a Ele o louvor,'),
      const Music(cipher: 'a Ele o domínio,'),
      const Music(cipher: 'ele é o Senhor (bis)'),
    ],
    hasCypher: false,
    ciphers: []);

Chant tudoEDoPai = Chant(
    title: 'Tudo é do Pai',
    category: 'Comunhão',
    lyrics: [
      const Music(cipher: 'Eu pensei que podia viver por mim mesmo,'),
      const Music(cipher: 'eu pensei que as coisas do mundo'),
      const Music(cipher: 'não iriam me derrubar.'),
      verse(),
      const Music(cipher: 'O orgulho tomou conta do meu ser'),
      const Music(cipher: 'e o pecado devastou o meu viver.'),
      const Music(cipher: 'Fui embora, disse ao Pai:'),
      const Music(cipher: '-Dá-me o que é meu.'),
      const Music(cipher: 'Dá-me a parte que me cabe da herança,'),
      const Music(cipher: 'fui pro mundo, gastei tudo,'),
      const Music(cipher: 'me restou só o pecado'),
      const Music(cipher: 'e hoje eu sei que nada é meu'),
      const Music(cipher: 'tudo é do Pai.'),
      verse(),
      const Refrao(cipher: 'Tudo é do Pai, toda honra toda a glória'),
      const Refrao(cipher: 'é dele a vitória alcançada em minha vida.'),
      const Refrao(cipher: 'Tudo é do Pai, se sou fraco e pecador,'),
      const Refrao(cipher: 'bem mais forte é o meu Senhor'),
      const Refrao(cipher: 'que me cura por amor! (Bis)'),
    ],
    hasCypher: false,
    ciphers: []);

Chant amarTeMais = Chant(
    title: 'Amar-te mais',
    category: 'Comunhão',
    lyrics: [
      const Music(cipher: 'Amar-te mais que a mim mesmo,'),
      const Music(cipher: 'amar-te mais que tudo o que há aqui!'),
      const Music(cipher: 'Amar-te mais que aos mais queridos,'),
      const Music(cipher: 'amar-te e dar a vida só por ti!(2x)'),
      verse(),
      const Music(cipher: 'Com minhas forças,'),
      const Music(cipher: 'com minha alma,'),
      const Music(cipher: 'de todo o coração,'),
      const Music(cipher: 'viverei eu só pra ti amar,'),
      const Music(cipher: 'amar-te, amar-te, amar-te'),
      const Music(cipher: 'e dar a vida só pó ti!'),
    ],
    hasCypher: false,
    ciphers: []);
