import 'package:diasguto/models/chant.dart';
import 'package:diasguto/templates/cipher.dart';

List<Chant> marianos = [regacoAcolhedor, imaculadaMariaDeDeus, maezinha];

Chant regacoAcolhedor =
    Chant(title: 'Regaço acolhedor', category: 'Cântico Mariano', ciphers: [
  const Music(cipher: "Oh, minh'alma"),
  const Music(cipher: 'Retorna à tua paz'),
  const Music(cipher: 'Como criança bem tranquila'),
  const Music(cipher: 'No regaço acolhedor de sua mãe'),
  verse(),
  const Music(cipher: "Oh, minh'alma"),
  const Music(cipher: 'Retorna à tua paz'),
  const Music(cipher: 'Como criança bem tranquila'),
  const Music(cipher: 'No regaço acolhedor de sua mãe'),
  verse(),
  const Music(cipher: 'Minha mãe é a Virgem Maria'),
  const Music(cipher: 'É ela que agora vai'),
  const Music(cipher: 'Me acolher, me abraçar'),
  const Music(cipher: 'Me perdoar, me compreender'),
  verse(),
  const Music(cipher: 'Me acalmar, me ensinar'),
  const Music(cipher: 'Me educar'),
  const Music(cipher: 'Me formar, me amar'),
  verse(),
  const Music(cipher: 'Minha mãe é a Virgem Maria'),
  const Music(cipher: 'É ela que agora vai'),
  const Music(cipher: 'Me acolher, me abraçar'),
  const Music(cipher: 'Me perdoar, me compreender'),
  verse(),
  const Music(cipher: 'Me acalmar, me ensinar'),
  const Music(cipher: 'Me educar'),
  const Music(cipher: 'Me formar, me amar'),
  verse(),
  const Music(cipher: "Oh, minh'alma"),
  const Music(cipher: 'Retorna à tua paz'),
]);

Chant imaculadaMariaDeDeus = Chant(
    title: 'Imaculada Maria de Deus',
    category: 'Cântico Mariano',
    ciphers: [
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
      verse(),
      const Music(cipher: 'Um coração que era sim para a vida'),
      const Music(cipher: 'Um coração que era sim para o irmão'),
      const Music(cipher: 'Um coração que era sim para Deus'),
      const Music(cipher: 'Reino de Deus renovando este chão'),
      verse(),
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
      verse(),
      const Music(cipher: 'Olhos abertos pra sede do povo'),
      const Music(cipher: 'Passo bem firme que o medo desterra'),
      const Music(cipher: 'Mãos estendidas que os tronos renegam'),
      const Music(cipher: 'Reino de Deus que renova esta terra'),
      verse(),
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
      verse(),
      const Music(cipher: 'Faça-se, ó Pai, Vossa plena vontade'),
      const Music(cipher: 'Que os nossos passos se tornem memória'),
      const Music(cipher: 'Do amor fiel que Maria gerou'),
      const Music(cipher: 'Reino de Deus atuando na história'),
      verse(),
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
    ]);

Chant perfe = Chant(
    title: 'Perfeito é quem te criou',
    category: 'Cântico Mariano',
    ciphers: [
      const Music(cipher: 'Se um dia um anjo declarou'),
      const Music(cipher: 'que tu era cheia de Deus'),
      const Music(cipher: 'agora penso quem sou eu'),
      const Music(cipher: 'para não te dizer também,'),
      const Music(cipher: 'cheia de graça ó mãe'),
      const Music(cipher: 'cheia de graça o mãe, agraciada.'),
      verse(),
      const Music(cipher: 'Se a palavra ensinou'),
      const Music(cipher: 'que todos hão de concordar'),
      const Music(cipher: 'e as gerações te proclamar'),
      const Music(cipher: 'agora eu também direi'),
      const Music(cipher: 'tu és bendita ó mãe,'),
      const Music(cipher: 'tu és bendita ó mãe bem aventurada.'),
      verse(),
      const Music(cipher: 'Surgiu um grande sinal no céu'),
      const Music(cipher: 'uma mulher revestida de sol'),
      const Music(cipher: 'a lua debaixo dos seus pés'),
      const Music(cipher: 'e na cabeça uma coroa.'),
      verse(),
      const Music(cipher: 'Não há como se comparar'),
      const Music(cipher: 'perfeito é quem te criou'),
      const Music(cipher: 'se o criador te coroou:'),
      verse(),
      const Refrao(cipher: 'Te coroamos ó mãe.'),
      const Refrao(cipher: 'Te coroamos ó mãe.'),
      const Refrao(cipher: 'Te coroamos ó mãe.'),
      const Refrao(cipher: 'Nossa rainha. (3x)'),
    ]);

Chant maezinha =
    Chant(title: 'Mãezinha do céu', category: 'Cântico Mariano', ciphers: [
  const Music(cipher: 'Mãezinha do céu, eu não sei rezar'),
  const Music(cipher: 'eu só sei dizer, que eu quero te amar'),
  verse(),
  const Refrao(cipher: 'Azul é teu manto;'),
  const Refrao(cipher: 'branco é teu véu;'),
  const Refrao(cipher: 'mãezinha eu quero, te ver lá no céu'),
  verse(),
  const Music(cipher: 'Mãezinha do céu, mão do puro amor'),
  const Music(cipher: 'Jesus é teu filho e eu tambem sou'),
  verse(),
  const Refrao(cipher: 'Azul é teu manto;'),
  const Refrao(cipher: 'branco é teu véu;'),
  const Refrao(cipher: 'mãezinha eu quero, te ver lá no céu'),
  verse(),
  const Music(cipher: 'Mãezinha do céu'),
  const Music(cipher: 'vou te consagrar,'),
  const Music(cipher: 'a minha inocência'),
  const Music(cipher: 'guarda sem cessar'),
  verse(),
  const Refrao(cipher: 'Azul é teu manto;'),
  const Refrao(cipher: 'branco é teu véu;'),
  const Refrao(cipher: 'mãezinha eu quero, te ver lá no céu'),
  verse(),
]);
