import 'package:diasguto/models/chant.dart';
import 'package:diasguto/templates/cipher.dart';

List<Chant> marianos = [regacoAcolhedor];

Chant regacoAcolhedor =
    Chant(title: 'Regaço acolhedor', category: 'Cântico Mariano', ciphers: [
  const Music(cipher: "Oh, minh'alma"),
  const Music(cipher: 'Retorna à tua paz'),
  const Music(cipher: 'Como criança bem tranquila'),
  const Music(cipher: 'No regaço acolhedor de sua mãe'),
  verse(),
  const Music(cipher: "Oh, minh'alma"),
  const Music(cipher: 'Retorna à tua paz'),
  const Music(cipher: 'Como criança bem tranquila'),
  const Music(cipher: 'No regaço acolhedor de sua mãe'),
  verse(),
  const Music(cipher: 'Minha mãe é a Virgem Maria'),
  const Music(cipher: 'É ela que agora vai'),
  const Music(cipher: 'Me acolher, me abraçar'),
  const Music(cipher: 'Me perdoar, me compreender'),
  verse(),
  const Music(cipher: 'Me acalmar, me ensinar'),
  const Music(cipher: 'Me educar'),
  const Music(cipher: 'Me formar, me amar'),
  verse(),
  const Music(cipher: 'Minha mãe é a Virgem Maria'),
  const Music(cipher: 'É ela que agora vai'),
  const Music(cipher: 'Me acolher, me abraçar'),
  const Music(cipher: 'Me perdoar, me compreender'),
  verse(),
  const Music(cipher: 'Me acalmar, me ensinar'),
  const Music(cipher: 'Me educar'),
  const Music(cipher: 'Me formar, me amar'),
  verse(),
  const Music(cipher: "Oh, minh'alma"),
  const Music(cipher: 'Retorna à tua paz'),
]);

Chant imaculadaMariaDeDeus = Chant(
    title: 'Imaculada Maria de Deus',
    category: 'Cântico Mariano',
    ciphers: [
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
      verse(),
      const Music(cipher: 'Um coração que era sim para a vida'),
      const Music(cipher: 'Um coração que era sim para o irmão'),
      const Music(cipher: 'Um coração que era sim para Deus'),
      const Music(cipher: 'Reino de Deus renovando este chão'),
      verse(),
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
      verse(),
      const Music(cipher: 'Olhos abertos pra sede do povo'),
      const Music(cipher: 'Passo bem firme que o medo desterra'),
      const Music(cipher: 'Mãos estendidas que os tronos renegam'),
      const Music(cipher: 'Reino de Deus que renova esta terra'),
      verse(),
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
      verse(),
      const Music(cipher: 'Faça-se, ó Pai, Vossa plena vontade'),
      const Music(cipher: 'Que os nossos passos se tornem memória'),
      const Music(cipher: 'Do amor fiel que Maria gerou'),
      const Music(cipher: 'Reino de Deus atuando na história'),
      verse(),
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
    ]);
