import 'package:diasguto/models/chant.dart';
import 'package:diasguto/templates/cipher.dart';

List<Chant> marianos = [
  regacoAcolhedor,
  imaculadaMariaDeDeus,
  maezinha,
  cenaculoDeAmor,
  hinoAAbadia,
  hinoAAparecida
];

Chant regacoAcolhedor = Chant(
    title: 'Regaço acolhedor',
    category: 'Cântico Mariano',
    lyrics: [
      const Music(cipher: "Oh, minh'alma"),
      const Music(cipher: 'Retorna à tua paz'),
      const Music(cipher: 'Como criança bem tranquila'),
      const Music(cipher: 'No regaço acolhedor de sua mãe (bis)'),
      verse(),
      const Music(cipher: 'Minha mãe é a Virgem Maria'),
      const Music(cipher: 'É ela que agora vai'),
      const Music(cipher: 'Me acolher, me abraçar'),
      const Music(cipher: 'Me perdoar, me compreender'),
      verse(),
      const Music(cipher: 'Me acalmar, me ensinar'),
      const Music(cipher: 'Me educar'),
      const Music(cipher: 'Me formar, me amar'),
      verse(),
      const Music(cipher: "Oh, minh'alma"),
      const Music(cipher: 'Retorna à tua paz'),
    ],
    ciphers: [
      Cifra(cipher: "G7M      A9       Bm7"),
      Music(cipher: "Oh, minh'alma retorna à tua paz"),
      Cifra(cipher: "G7M         A9"),
      Music(cipher: "Como criança bem tranquila"),
      Cifra(cipher: "D7M   A/C#       Bm7"),
      Music(cipher: "No regaço acolhedor de sua mãe.(2x)"),
      Cifra(cipher: "G7M A            D7M"),
      Music(cipher: "Minha Mãe é a Virgem Maria"),
      Cifra(cipher: "A/C#    Bm7  Bm/A      G7M         A9"),
      Music(cipher: "É ela que agora vai me acolher, me abraçar,"),
      Cifra(cipher: "D7M   A/C#      Bm7"),
      Music(cipher: "me perdoar, me compreender,"),
      Cifra(cipher: "G7M         A"),
      Music(cipher: "me acalmar, me ensinar,"),
      Cifra(cipher: "       Bm7"),
      Music(cipher: "me educar,"),
      Cifra(cipher: "      G7M A9  Bm7"),
      Music(cipher: "me formar, me amar. (2x)"),
      Cifra(cipher: "G7M      A        Bm7"),
      Music(cipher: "Oh, minh'alma retorna à tua paz..."),
    ],
    hasCypher: true);

Chant imaculadaMariaDeDeus = Chant(
    title: 'Imaculada Maria de Deus',
    category: 'Cântico Mariano',
    lyrics: [
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
      verse(),
      const Music(cipher: 'Um coração que era sim para a vida'),
      const Music(cipher: 'Um coração que era sim para o irmão'),
      const Music(cipher: 'Um coração que era sim para Deus'),
      const Music(cipher: 'Reino de Deus renovando este chão'),
      verse(),
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
      verse(),
      const Music(cipher: 'Olhos abertos pra sede do povo'),
      const Music(cipher: 'Passo bem firme que o medo desterra'),
      const Music(cipher: 'Mãos estendidas que os tronos renegam'),
      const Music(cipher: 'Reino de Deus que renova esta terra'),
      verse(),
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
      verse(),
      const Music(cipher: 'Faça-se, ó Pai, Vossa plena vontade'),
      const Music(cipher: 'Que os nossos passos se tornem memória'),
      const Music(cipher: 'Do amor fiel que Maria gerou'),
      const Music(cipher: 'Reino de Deus atuando na história'),
      verse(),
      const Refrao(cipher: 'Imaculada, Maria de Deus'),
      const Refrao(cipher: 'Coração pobre acolhendo Jesus'),
      const Refrao(cipher: 'Imaculada, Maria do povo'),
      const Refrao(cipher: 'Mãe dos aflitos que estão junto à cruz'),
    ],
    hasCypher: false,
    ciphers: []);

Chant perfe = Chant(
    title: 'Perfeito é quem te criou',
    category: 'Cântico Mariano',
    lyrics: [
      const Music(cipher: 'Se um dia um anjo declarou'),
      const Music(cipher: 'que tu era cheia de Deus'),
      const Music(cipher: 'agora penso quem sou eu'),
      const Music(cipher: 'para não te dizer também,'),
      const Music(cipher: 'cheia de graça ó mãe'),
      const Music(cipher: 'cheia de graça o mãe, agraciada.'),
      verse(),
      const Music(cipher: 'Se a palavra ensinou'),
      const Music(cipher: 'que todos hão de concordar'),
      const Music(cipher: 'e as gerações te proclamar'),
      const Music(cipher: 'agora eu também direi'),
      const Music(cipher: 'tu és bendita ó mãe,'),
      const Music(cipher: 'tu és bendita ó mãe bem aventurada.'),
      verse(),
      const Music(cipher: 'Surgiu um grande sinal no céu'),
      const Music(cipher: 'uma mulher revestida de sol'),
      const Music(cipher: 'a lua debaixo dos seus pés'),
      const Music(cipher: 'e na cabeça uma coroa.'),
      verse(),
      const Music(cipher: 'Não há como se comparar'),
      const Music(cipher: 'perfeito é quem te criou'),
      const Music(cipher: 'se o criador te coroou:'),
      verse(),
      const Refrao(cipher: 'Te coroamos ó mãe.'),
      const Refrao(cipher: 'Te coroamos ó mãe.'),
      const Refrao(cipher: 'Te coroamos ó mãe.'),
      const Refrao(cipher: 'Nossa rainha. (3x)'),
    ],
    hasCypher: false,
    ciphers: []);

Chant maezinha = Chant(
    title: 'Mãezinha do céu',
    category: 'Cântico Mariano',
    lyrics: [
      const Music(cipher: 'Mãezinha do céu, eu não sei rezar'),
      const Music(cipher: 'eu só sei dizer, que eu quero te amar'),
      verse(),
      const Refrao(cipher: 'Azul é teu manto;'),
      const Refrao(cipher: 'branco é teu véu;'),
      const Refrao(cipher: 'mãezinha eu quero, te ver lá no céu'),
      verse(),
      const Music(cipher: 'Mãezinha do céu, mão do puro amor'),
      const Music(cipher: 'Jesus é teu filho e eu tambem sou'),
      verse(),
      const Refrao(cipher: 'Azul é teu manto;'),
      const Refrao(cipher: 'branco é teu véu;'),
      const Refrao(cipher: 'mãezinha eu quero, te ver lá no céu'),
      verse(),
      const Music(cipher: 'Mãezinha do céu'),
      const Music(cipher: 'vou te consagrar,'),
      const Music(cipher: 'a minha inocência'),
      const Music(cipher: 'guarda sem cessar'),
      verse(),
      const Refrao(cipher: 'Azul é teu manto;'),
      const Refrao(cipher: 'branco é teu véu;'),
      const Refrao(cipher: 'mãezinha eu quero, te ver lá no céu'),
      verse(),
    ],
    hasCypher: false,
    ciphers: []);

Chant cenaculoDeAmor = Chant(
    title: 'Cenáculo de amor',
    category: 'Cântico Mariano',
    lyrics: [
      const Music(cipher: 'Reunidos aqui,'),
      const Music(cipher: 'num Cenáculo de amor,'),
      const Music(cipher: 'pedimos forças '),
      const Music(cipher: 'pelas mãos de Maria.'),
      const Music(cipher: 'Ela conhece bem todos seus queridos filhos'),
      const Music(cipher: ' e não deixará faltar para nós seu auxílio.'),
      verse(),
      const Refrao(cipher: 'Vinde, Espírito Santo! Vinde'),
      const Refrao(cipher: 'por meio da poderosa intercessão'),
      const Refrao(cipher: 'do Imaculado Coração de Maria.'),
      const Refrao(cipher: 'Vossa amadíssima Esposa.'),
      verse(),
    ],
    hasCypher: false,
    ciphers: []);

Chant hinoAAbadia = Chant(
    title: "Hino à nossa Senhora D'abadia",
    category: 'Cântico Mariano',
    lyrics: [
      const Music(cipher: '1. Óh! Filha do eterno Pai,'),
      const Music(cipher: 'de deus Filho Mãe pia,'),
      const Music(cipher: 'do Espírito Santo esposa...'),
      const Music(cipher: "OH Senhora D'Abadia. (Bis)"),
      verse(),
      Music(cipher: '2-Agora vos invocamos,'),
      const Music(cipher: 'em devota melodia.'),
      const Music(cipher: 'Levai ao Céu nossos votos...'),
      const Music(cipher: "OH Senhora D'Abadia. (Bis)"),
      verse(),
      Music(cipher: '3- Sois a alegria dos céus.'),
      const Music(cipher: 'Sois luz na noite sombria.'),
      const Music(cipher: 'Sois o terror do inferno...'),
      const Music(cipher: "OH Senhora D'Abadia.(bis)"),
      verse(),
      Music(cipher: '4- Sois a Torre de Davi.'),
      const Music(cipher: 'Dos fortes a valentia.'),
      const Music(cipher: 'Sois a chave que abre os céu...'),
      const Music(cipher: "OH Senhora D'Abadia. (bis)"),
      verse(),
      Music(cipher: '5- Se o vosso nome invocarmos.'),
      const Music(cipher: 'Nos momentos de agonia.'),
      const Music(cipher: 'Mostrais que sois nossa Mãe...'),
      const Music(cipher: "OH Senhora D'Abadia.(Bis)"),
      verse(),
      Music(cipher: '6- E por vossa intercessão'),
      const Music(cipher: 'e poderosa valia alcançai-nos Glória eterna...'),
      const Music(cipher: "OH Senhora D'Abadia.(Bis)"),
    ],
    hasCypher: false,
    ciphers: []);

Chant hinoAAparecida = Chant(
    title: 'Hino à Aparecida',
    category: 'Cântico Mariano',
    lyrics: [
      const Music(cipher: 'Viva a Mãe de Deus e nossa'),
      const Music(cipher: 'sem pecado concebida'),
      const Music(cipher: 'viva a Virgem Imaculada'),
      const Music(cipher: 'oh Senhora Aparecida'),
      verse(),
      Music(cipher: '1.No calvário junto a cruz'),
      const Music(cipher: 'com a alma de dor ferida'),
      const Music(cipher: 'Jesus vos fez nossa Mãe,'),
      const Music(cipher: 'Ó Senhora Aparecida.'),
      verse(),
      Music(cipher: '2.Protegei a Santa Igreja'),
      const Music(cipher: 'Ó Mãe terna e compadecida,'),
      const Music(cipher: 'protegei a nossa pátria'),
      const Music(cipher: 'Ó Senhora Aparecida.'),
      verse(),
      Music(cipher: '3.Aqui estão vossos devotos'),
      const Music(cipher: 'cheios de fé incendida'),
      const Music(cipher: 'de conforto e de esperança'),
      const Music(cipher: 'Ó Senhora Aparecida.'),
      verse(),
      Music(cipher: '4. Virgem santa, virgem bela,'),
      const Music(cipher: 'Mãe amável, Mãe querida amparai-nos,'),
      const Music(cipher: 'socorrei-nos Ó Senhora Aparecida.'),
      verse(),
      Music(cipher: '5. Velai por nossas famílias'),
      const Music(cipher: 'pela infância desvalida'),
      const Music(cipher: 'pelo povo brasileiro'),
      const Music(cipher: 'Ó Senhora Aparecida.'),
    ],
    hasCypher: false,
    ciphers: []);
